// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: app/grpc/service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{0}
}

type GatewayStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerStatus        `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Http3Servers  []*ServerStatus        `protobuf:"bytes,2,rep,name=http3_servers,json=http3Servers,proto3" json:"http3_servers,omitempty"`
	ServerConfigs []*GatewayServerConfig `protobuf:"bytes,3,rep,name=server_configs,json=serverConfigs,proto3" json:"server_configs,omitempty"`
	Middleware    *MiddlewareStatus      `protobuf:"bytes,4,opt,name=middleware,proto3" json:"middleware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayStatusResponse) Reset() {
	*x = GatewayStatusResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatusResponse) ProtoMessage() {}

func (x *GatewayStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatusResponse.ProtoReflect.Descriptor instead.
func (*GatewayStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayStatusResponse) GetServers() []*ServerStatus {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *GatewayStatusResponse) GetHttp3Servers() []*ServerStatus {
	if x != nil {
		return x.Http3Servers
	}
	return nil
}

func (x *GatewayStatusResponse) GetServerConfigs() []*GatewayServerConfig {
	if x != nil {
		return x.ServerConfigs
	}
	return nil
}

func (x *GatewayStatusResponse) GetMiddleware() *MiddlewareStatus {
	if x != nil {
		return x.Middleware
	}
	return nil
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_app_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FrontProxyStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Balancer      string                 `protobuf:"bytes,6,opt,name=balancer,proto3" json:"balancer,omitempty"`
	CacheEnabled  bool                   `protobuf:"varint,7,opt,name=cache_enabled,json=cacheEnabled,proto3" json:"cache_enabled,omitempty"`
	ServerCount   int32                  `protobuf:"varint,8,opt,name=server_count,json=serverCount,proto3" json:"server_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontProxyStatusResponse) Reset() {
	*x = FrontProxyStatusResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontProxyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontProxyStatusResponse) ProtoMessage() {}

func (x *FrontProxyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontProxyStatusResponse.ProtoReflect.Descriptor instead.
func (*FrontProxyStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *FrontProxyStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *FrontProxyStatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FrontProxyStatusResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *FrontProxyStatusResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FrontProxyStatusResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *FrontProxyStatusResponse) GetBalancer() string {
	if x != nil {
		return x.Balancer
	}
	return ""
}

func (x *FrontProxyStatusResponse) GetCacheEnabled() bool {
	if x != nil {
		return x.CacheEnabled
	}
	return false
}

func (x *FrontProxyStatusResponse) GetServerCount() int32 {
	if x != nil {
		return x.ServerCount
	}
	return 0
}

type ModifierManagerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModifierCount int32                  `protobuf:"varint,1,opt,name=modifier_count,json=modifierCount,proto3" json:"modifier_count,omitempty"`
	Modifiers     []*ModifierInfo        `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifierManagerInfoResponse) Reset() {
	*x = ModifierManagerInfoResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifierManagerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifierManagerInfoResponse) ProtoMessage() {}

func (x *ModifierManagerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifierManagerInfoResponse.ProtoReflect.Descriptor instead.
func (*ModifierManagerInfoResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *ModifierManagerInfoResponse) GetModifierCount() int32 {
	if x != nil {
		return x.ModifierCount
	}
	return 0
}

func (x *ModifierManagerInfoResponse) GetModifiers() []*ModifierInfo {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type ModifierInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifierInfo) Reset() {
	*x = ModifierInfo{}
	mi := &file_app_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifierInfo) ProtoMessage() {}

func (x *ModifierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifierInfo.ProtoReflect.Descriptor instead.
func (*ModifierInfo) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *ModifierInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModifierInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type StatServerConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EnableStat       bool                   `protobuf:"varint,2,opt,name=enable_stat,json=enableStat,proto3" json:"enable_stat,omitempty"`
	SyncDuration     int32                  `protobuf:"varint,3,opt,name=sync_duration,json=syncDuration,proto3" json:"sync_duration,omitempty"`
	SaveDuration     int32                  `protobuf:"varint,4,opt,name=save_duration,json=saveDuration,proto3" json:"save_duration,omitempty"`
	SaveFile         string                 `protobuf:"bytes,5,opt,name=save_file,json=saveFile,proto3" json:"save_file,omitempty"`
	GeoFile          string                 `protobuf:"bytes,6,opt,name=geo_file,json=geoFile,proto3" json:"geo_file,omitempty"`
	DomainFile       string                 `protobuf:"bytes,7,opt,name=domain_file,json=domainFile,proto3" json:"domain_file,omitempty"`
	GeoDb            string                 `protobuf:"bytes,8,opt,name=geo_db,json=geoDb,proto3" json:"geo_db,omitempty"`
	SequenceEnabled  bool                   `protobuf:"varint,9,opt,name=sequence_enabled,json=sequenceEnabled,proto3" json:"sequence_enabled,omitempty"`
	SequenceInterval int32                  `protobuf:"varint,10,opt,name=sequence_interval,json=sequenceInterval,proto3" json:"sequence_interval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatServerConfigResponse) Reset() {
	*x = StatServerConfigResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatServerConfigResponse) ProtoMessage() {}

func (x *StatServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatServerConfigResponse.ProtoReflect.Descriptor instead.
func (*StatServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *StatServerConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StatServerConfigResponse) GetEnableStat() bool {
	if x != nil {
		return x.EnableStat
	}
	return false
}

func (x *StatServerConfigResponse) GetSyncDuration() int32 {
	if x != nil {
		return x.SyncDuration
	}
	return 0
}

func (x *StatServerConfigResponse) GetSaveDuration() int32 {
	if x != nil {
		return x.SaveDuration
	}
	return 0
}

func (x *StatServerConfigResponse) GetSaveFile() string {
	if x != nil {
		return x.SaveFile
	}
	return ""
}

func (x *StatServerConfigResponse) GetGeoFile() string {
	if x != nil {
		return x.GeoFile
	}
	return ""
}

func (x *StatServerConfigResponse) GetDomainFile() string {
	if x != nil {
		return x.DomainFile
	}
	return ""
}

func (x *StatServerConfigResponse) GetGeoDb() string {
	if x != nil {
		return x.GeoDb
	}
	return ""
}

func (x *StatServerConfigResponse) GetSequenceEnabled() bool {
	if x != nil {
		return x.SequenceEnabled
	}
	return false
}

func (x *StatServerConfigResponse) GetSequenceInterval() int32 {
	if x != nil {
		return x.SequenceInterval
	}
	return 0
}

type RuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	RssBytes      int64                  `protobuf:"varint,3,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	Goroutines    int32                  `protobuf:"varint,4,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	NetIoBlock    bool                   `protobuf:"varint,5,opt,name=net_io_block,json=netIoBlock,proto3" json:"net_io_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeResponse) Reset() {
	*x = RuntimeResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResponse) ProtoMessage() {}

func (x *RuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResponse.ProtoReflect.Descriptor instead.
func (*RuntimeResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeResponse) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *RuntimeResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RuntimeResponse) GetRssBytes() int64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *RuntimeResponse) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *RuntimeResponse) GetNetIoBlock() bool {
	if x != nil {
		return x.NetIoBlock
	}
	return false
}

type DomainMapResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domains        []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	DomainsMap     map[string]string `protobuf:"bytes,2,rep,name=domains_map,json=domainsMap,proto3" json:"domains_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DomainFrontMap map[string]string      `protobuf:"bytes,3,rep,name=domain_front_map,json=domainFrontMap,proto3" json:"domain_front_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DomainMapResponse) Reset() {
	*x = DomainMapResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainMapResponse) ProtoMessage() {}

func (x *DomainMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainMapResponse.ProtoReflect.Descriptor instead.
func (*DomainMapResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *DomainMapResponse) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DomainMapResponse) GetDomainsMap() map[string]string {
	if x != nil {
		return x.DomainsMap
	}
	return nil
}

func (x *DomainMapResponse) GetDomainFrontMap() map[string]string {
	if x != nil {
		return x.DomainFrontMap
	}
	return nil
}

type ServiceMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      string                 `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMap) Reset() {
	*x = ServiceMap{}
	mi := &file_app_grpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMap) ProtoMessage() {}

func (x *ServiceMap) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMap.ProtoReflect.Descriptor instead.
func (*ServiceMap) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceMap) GetFrontend() string {
	if x != nil {
		return x.Frontend
	}
	return ""
}

func (x *ServiceMap) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type DomainPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*DomainPorts         `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainPortsResponse) Reset() {
	*x = DomainPortsResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainPortsResponse) ProtoMessage() {}

func (x *DomainPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainPortsResponse.ProtoReflect.Descriptor instead.
func (*DomainPortsResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *DomainPortsResponse) GetPorts() []*DomainPorts {
	if x != nil {
		return x.Ports
	}
	return nil
}

type DomainPorts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Ports         []int32                `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainPorts) Reset() {
	*x = DomainPorts{}
	mi := &file_app_grpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainPorts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainPorts) ProtoMessage() {}

func (x *DomainPorts) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainPorts.ProtoReflect.Descriptor instead.
func (*DomainPorts) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *DomainPorts) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainPorts) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_app_grpc_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadConfigRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{13}
}

func (x *ReloadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DumpRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpRuntimeRequest) Reset() {
	*x = DumpRuntimeRequest{}
	mi := &file_app_grpc_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpRuntimeRequest) ProtoMessage() {}

func (x *DumpRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpRuntimeRequest.ProtoReflect.Descriptor instead.
func (*DumpRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{14}
}

func (x *DumpRuntimeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DomainServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainServiceRequest) Reset() {
	*x = DomainServiceRequest{}
	mi := &file_app_grpc_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainServiceRequest) ProtoMessage() {}

func (x *DomainServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainServiceRequest.ProtoReflect.Descriptor instead.
func (*DomainServiceRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{15}
}

func (x *DomainServiceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_app_grpc_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{16}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GatewayServerConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port           int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	UseHttp2       bool                   `protobuf:"varint,4,opt,name=use_http2,json=useHttp2,proto3" json:"use_http2,omitempty"`
	Protocol       string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Enabled        bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MaxRequestBody int64                  `protobuf:"varint,7,opt,name=max_request_body,json=maxRequestBody,proto3" json:"max_request_body,omitempty"`
	Domains        []string               `protobuf:"bytes,8,rep,name=domains,proto3" json:"domains,omitempty"`
	AutoRedirect   bool                   `protobuf:"varint,9,opt,name=auto_redirect,json=autoRedirect,proto3" json:"auto_redirect,omitempty"`
	UseWebsocket   bool                   `protobuf:"varint,10,opt,name=use_websocket,json=useWebsocket,proto3" json:"use_websocket,omitempty"`
	WsDomains      []string               `protobuf:"bytes,11,rep,name=ws_domains,json=wsDomains,proto3" json:"ws_domains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayServerConfig) Reset() {
	*x = GatewayServerConfig{}
	mi := &file_app_grpc_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayServerConfig) ProtoMessage() {}

func (x *GatewayServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayServerConfig.ProtoReflect.Descriptor instead.
func (*GatewayServerConfig) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{17}
}

func (x *GatewayServerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayServerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GatewayServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GatewayServerConfig) GetUseHttp2() bool {
	if x != nil {
		return x.UseHttp2
	}
	return false
}

func (x *GatewayServerConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *GatewayServerConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GatewayServerConfig) GetMaxRequestBody() int64 {
	if x != nil {
		return x.MaxRequestBody
	}
	return 0
}

func (x *GatewayServerConfig) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *GatewayServerConfig) GetAutoRedirect() bool {
	if x != nil {
		return x.AutoRedirect
	}
	return false
}

func (x *GatewayServerConfig) GetUseWebsocket() bool {
	if x != nil {
		return x.UseWebsocket
	}
	return false
}

func (x *GatewayServerConfig) GetWsDomains() []string {
	if x != nil {
		return x.WsDomains
	}
	return nil
}

type MiddlewareStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GzipEnabled         bool                   `protobuf:"varint,1,opt,name=gzip_enabled,json=gzipEnabled,proto3" json:"gzip_enabled,omitempty"`
	GzipLevel           int32                  `protobuf:"varint,2,opt,name=gzip_level,json=gzipLevel,proto3" json:"gzip_level,omitempty"`
	GzipTypes           []string               `protobuf:"bytes,3,rep,name=gzip_types,json=gzipTypes,proto3" json:"gzip_types,omitempty"`
	NoCache             bool                   `protobuf:"varint,4,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	SecureHeader        bool                   `protobuf:"varint,5,opt,name=secure_header,json=secureHeader,proto3" json:"secure_header,omitempty"`
	TraceEnabled        bool                   `protobuf:"varint,6,opt,name=trace_enabled,json=traceEnabled,proto3" json:"trace_enabled,omitempty"`
	TraceId             string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CorsEnabled         bool                   `protobuf:"varint,8,opt,name=cors_enabled,json=corsEnabled,proto3" json:"cors_enabled,omitempty"`
	CorsMethod          []string               `protobuf:"bytes,9,rep,name=cors_method,json=corsMethod,proto3" json:"cors_method,omitempty"`
	CorsOrigin          []string               `protobuf:"bytes,10,rep,name=cors_origin,json=corsOrigin,proto3" json:"cors_origin,omitempty"`
	CorsHeader          []string               `protobuf:"bytes,11,rep,name=cors_header,json=corsHeader,proto3" json:"cors_header,omitempty"`
	SanitizerEnabled    bool                   `protobuf:"varint,12,opt,name=sanitizer_enabled,json=sanitizerEnabled,proto3" json:"sanitizer_enabled,omitempty"`
	DomainCheckEnabled  bool                   `protobuf:"varint,13,opt,name=domain_check_enabled,json=domainCheckEnabled,proto3" json:"domain_check_enabled,omitempty"`
	ImageProtectEnabled bool                   `protobuf:"varint,14,opt,name=image_protect_enabled,json=imageProtectEnabled,proto3" json:"image_protect_enabled,omitempty"`
	ImageType           []string               `protobuf:"bytes,15,rep,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
	AllowReferer        []string               `protobuf:"bytes,16,rep,name=allow_referer,json=allowReferer,proto3" json:"allow_referer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MiddlewareStatus) Reset() {
	*x = MiddlewareStatus{}
	mi := &file_app_grpc_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareStatus) ProtoMessage() {}

func (x *MiddlewareStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareStatus.ProtoReflect.Descriptor instead.
func (*MiddlewareStatus) Descriptor() ([]byte, []int) {
	return file_app_grpc_service_proto_rawDescGZIP(), []int{18}
}

func (x *MiddlewareStatus) GetGzipEnabled() bool {
	if x != nil {
		return x.GzipEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetGzipLevel() int32 {
	if x != nil {
		return x.GzipLevel
	}
	return 0
}

func (x *MiddlewareStatus) GetGzipTypes() []string {
	if x != nil {
		return x.GzipTypes
	}
	return nil
}

func (x *MiddlewareStatus) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

func (x *MiddlewareStatus) GetSecureHeader() bool {
	if x != nil {
		return x.SecureHeader
	}
	return false
}

func (x *MiddlewareStatus) GetTraceEnabled() bool {
	if x != nil {
		return x.TraceEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MiddlewareStatus) GetCorsEnabled() bool {
	if x != nil {
		return x.CorsEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetCorsMethod() []string {
	if x != nil {
		return x.CorsMethod
	}
	return nil
}

func (x *MiddlewareStatus) GetCorsOrigin() []string {
	if x != nil {
		return x.CorsOrigin
	}
	return nil
}

func (x *MiddlewareStatus) GetCorsHeader() []string {
	if x != nil {
		return x.CorsHeader
	}
	return nil
}

func (x *MiddlewareStatus) GetSanitizerEnabled() bool {
	if x != nil {
		return x.SanitizerEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetDomainCheckEnabled() bool {
	if x != nil {
		return x.DomainCheckEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetImageProtectEnabled() bool {
	if x != nil {
		return x.ImageProtectEnabled
	}
	return false
}

func (x *MiddlewareStatus) GetImageType() []string {
	if x != nil {
		return x.ImageType
	}
	return nil
}

func (x *MiddlewareStatus) GetAllowReferer() []string {
	if x != nil {
		return x.AllowReferer
	}
	return nil
}

var File_app_grpc_service_proto protoreflect.FileDescriptor

const file_app_grpc_service_proto_rawDesc = "" +
	"\n" +
	"\x16app/grpc/service.proto\x12\vgrpc_server\"\a\n" +
	"\x05Empty\"\x94\x02\n" +
	"\x15GatewayStatusResponse\x123\n" +
	"\aservers\x18\x01 \x03(\v2\x19.grpc_server.ServerStatusR\aservers\x12>\n" +
	"\rhttp3_servers\x18\x02 \x03(\v2\x19.grpc_server.ServerStatusR\fhttp3Servers\x12G\n" +
	"\x0eserver_configs\x18\x03 \x03(\v2 .grpc_server.GatewayServerConfigR\rserverConfigs\x12=\n" +
	"\n" +
	"middleware\x18\x04 \x01(\v2\x1d.grpc_server.MiddlewareStatusR\n" +
	"middleware\"V\n" +
	"\fServerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xe8\x01\n" +
	"\x18FrontProxyStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1a\n" +
	"\bbalancer\x18\x06 \x01(\tR\bbalancer\x12#\n" +
	"\rcache_enabled\x18\a \x01(\bR\fcacheEnabled\x12!\n" +
	"\fserver_count\x18\b \x01(\x05R\vserverCount\"}\n" +
	"\x1bModifierManagerInfoResponse\x12%\n" +
	"\x0emodifier_count\x18\x01 \x01(\x05R\rmodifierCount\x127\n" +
	"\tmodifiers\x18\x02 \x03(\v2\x19.grpc_server.ModifierInfoR\tmodifiers\"<\n" +
	"\fModifierInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\xe7\x02\n" +
	"\x18StatServerConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\venable_stat\x18\x02 \x01(\bR\n" +
	"enableStat\x12#\n" +
	"\rsync_duration\x18\x03 \x01(\x05R\fsyncDuration\x12#\n" +
	"\rsave_duration\x18\x04 \x01(\x05R\fsaveDuration\x12\x1b\n" +
	"\tsave_file\x18\x05 \x01(\tR\bsaveFile\x12\x19\n" +
	"\bgeo_file\x18\x06 \x01(\tR\ageoFile\x12\x1f\n" +
	"\vdomain_file\x18\a \x01(\tR\n" +
	"domainFile\x12\x15\n" +
	"\x06geo_db\x18\b \x01(\tR\x05geoDb\x12)\n" +
	"\x10sequence_enabled\x18\t \x01(\bR\x0fsequenceEnabled\x12+\n" +
	"\x11sequence_interval\x18\n" +
	" \x01(\x05R\x10sequenceInterval\"\xa5\x01\n" +
	"\x0fRuntimeResponse\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1b\n" +
	"\trss_bytes\x18\x03 \x01(\x03R\brssBytes\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x04 \x01(\x05R\n" +
	"goroutines\x12 \n" +
	"\fnet_io_block\x18\x05 \x01(\bR\n" +
	"netIoBlock\"\xf7\x02\n" +
	"\x11DomainMapResponse\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\x12O\n" +
	"\vdomains_map\x18\x02 \x03(\v2..grpc_server.DomainMapResponse.DomainsMapEntryR\n" +
	"domainsMap\x12\\\n" +
	"\x10domain_front_map\x18\x03 \x03(\v22.grpc_server.DomainMapResponse.DomainFrontMapEntryR\x0edomainFrontMap\x1aV\n" +
	"\x0fDomainsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.grpc_server.ServiceMapR\x05value:\x028\x01\x1aA\n" +
	"\x13DomainFrontMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\n" +
	"ServiceMap\x12\x1a\n" +
	"\bfrontend\x18\x01 \x01(\tR\bfrontend\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\"E\n" +
	"\x13DomainPortsResponse\x12.\n" +
	"\x05ports\x18\x01 \x03(\v2\x18.grpc_server.DomainPortsR\x05ports\";\n" +
	"\vDomainPorts\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x05R\x05ports\")\n" +
	"\x13ReloadConfigRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\"F\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x12DumpRuntimeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x14DomainServiceRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd1\x02\n" +
	"\x13GatewayServerConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\tuse_http2\x18\x04 \x01(\bR\buseHttp2\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12(\n" +
	"\x10max_request_body\x18\a \x01(\x03R\x0emaxRequestBody\x12\x18\n" +
	"\adomains\x18\b \x03(\tR\adomains\x12#\n" +
	"\rauto_redirect\x18\t \x01(\bR\fautoRedirect\x12#\n" +
	"\ruse_websocket\x18\n" +
	" \x01(\bR\fuseWebsocket\x12\x1d\n" +
	"\n" +
	"ws_domains\x18\v \x03(\tR\twsDomains\"\xd0\x04\n" +
	"\x10MiddlewareStatus\x12!\n" +
	"\fgzip_enabled\x18\x01 \x01(\bR\vgzipEnabled\x12\x1d\n" +
	"\n" +
	"gzip_level\x18\x02 \x01(\x05R\tgzipLevel\x12\x1d\n" +
	"\n" +
	"gzip_types\x18\x03 \x03(\tR\tgzipTypes\x12\x19\n" +
	"\bno_cache\x18\x04 \x01(\bR\anoCache\x12#\n" +
	"\rsecure_header\x18\x05 \x01(\bR\fsecureHeader\x12#\n" +
	"\rtrace_enabled\x18\x06 \x01(\bR\ftraceEnabled\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12!\n" +
	"\fcors_enabled\x18\b \x01(\bR\vcorsEnabled\x12\x1f\n" +
	"\vcors_method\x18\t \x03(\tR\n" +
	"corsMethod\x12\x1f\n" +
	"\vcors_origin\x18\n" +
	" \x03(\tR\n" +
	"corsOrigin\x12\x1f\n" +
	"\vcors_header\x18\v \x03(\tR\n" +
	"corsHeader\x12+\n" +
	"\x11sanitizer_enabled\x18\f \x01(\bR\x10sanitizerEnabled\x120\n" +
	"\x14domain_check_enabled\x18\r \x01(\bR\x12domainCheckEnabled\x122\n" +
	"\x15image_protect_enabled\x18\x0e \x01(\bR\x13imageProtectEnabled\x12\x1d\n" +
	"\n" +
	"image_type\x18\x0f \x03(\tR\timageType\x12#\n" +
	"\rallow_referer\x18\x10 \x03(\tR\fallowReferer2\xa3\v\n" +
	"\n" +
	"AppService\x12J\n" +
	"\x10GetGatewayStatus\x12\x12.grpc_server.Empty\x1a\".grpc_server.GatewayStatusResponse\x12P\n" +
	"\x13GetFrontProxyStatus\x12\x12.grpc_server.Empty\x1a%.grpc_server.FrontProxyStatusResponse\x12V\n" +
	"\x16GetModifierManagerInfo\x12\x12.grpc_server.Empty\x1a(.grpc_server.ModifierManagerInfoResponse\x12P\n" +
	"\x13GetStatServerConfig\x12\x12.grpc_server.Empty\x1a%.grpc_server.StatServerConfigResponse\x12>\n" +
	"\n" +
	"GetRuntime\x12\x12.grpc_server.Empty\x1a\x1c.grpc_server.RuntimeResponse\x12B\n" +
	"\fGetDomainMap\x12\x12.grpc_server.Empty\x1a\x1e.grpc_server.DomainMapResponse\x12F\n" +
	"\x0eGetDomainPorts\x12\x12.grpc_server.Empty\x1a .grpc_server.DomainPortsResponse\x12S\n" +
	"\fReloadConfig\x12 .grpc_server.ReloadConfigRequest\x1a!.grpc_server.ReloadConfigResponse\x12E\n" +
	"\x12ReStartFrontServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12A\n" +
	"\x0eReStartGateway\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12C\n" +
	"\x10ReStartAPIServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12G\n" +
	"\x14ReStartBackendServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12G\n" +
	"\x14ReStartLatencyServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12C\n" +
	"\x10ReStartVPNServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12F\n" +
	"\x13ReStartTrojanServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12F\n" +
	"\x13ReStartAnyTLSServer\x12\x12.grpc_server.Empty\x1a\x1b.grpc_server.ActionResponse\x12T\n" +
	"\x12StartDomainService\x12!.grpc_server.DomainServiceRequest\x1a\x1b.grpc_server.ActionResponse\x12S\n" +
	"\x11StopDomainService\x12!.grpc_server.DomainServiceRequest\x1a\x1b.grpc_server.ActionResponse\x12K\n" +
	"\vDumpRuntime\x12\x1f.grpc_server.DumpRuntimeRequest\x1a\x1b.grpc_server.ActionResponseB\x14Z\x12Hamburger/app/grpcb\x06proto3"

var (
	file_app_grpc_service_proto_rawDescOnce sync.Once
	file_app_grpc_service_proto_rawDescData []byte
)

func file_app_grpc_service_proto_rawDescGZIP() []byte {
	file_app_grpc_service_proto_rawDescOnce.Do(func() {
		file_app_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_grpc_service_proto_rawDesc), len(file_app_grpc_service_proto_rawDesc)))
	})
	return file_app_grpc_service_proto_rawDescData
}

var file_app_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_app_grpc_service_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: grpc_server.Empty
	(*GatewayStatusResponse)(nil),       // 1: grpc_server.GatewayStatusResponse
	(*ServerStatus)(nil),                // 2: grpc_server.ServerStatus
	(*FrontProxyStatusResponse)(nil),    // 3: grpc_server.FrontProxyStatusResponse
	(*ModifierManagerInfoResponse)(nil), // 4: grpc_server.ModifierManagerInfoResponse
	(*ModifierInfo)(nil),                // 5: grpc_server.ModifierInfo
	(*StatServerConfigResponse)(nil),    // 6: grpc_server.StatServerConfigResponse
	(*RuntimeResponse)(nil),             // 7: grpc_server.RuntimeResponse
	(*DomainMapResponse)(nil),           // 8: grpc_server.DomainMapResponse
	(*ServiceMap)(nil),                  // 9: grpc_server.ServiceMap
	(*DomainPortsResponse)(nil),         // 10: grpc_server.DomainPortsResponse
	(*DomainPorts)(nil),                 // 11: grpc_server.DomainPorts
	(*ReloadConfigRequest)(nil),         // 12: grpc_server.ReloadConfigRequest
	(*ReloadConfigResponse)(nil),        // 13: grpc_server.ReloadConfigResponse
	(*DumpRuntimeRequest)(nil),          // 14: grpc_server.DumpRuntimeRequest
	(*DomainServiceRequest)(nil),        // 15: grpc_server.DomainServiceRequest
	(*ActionResponse)(nil),              // 16: grpc_server.ActionResponse
	(*GatewayServerConfig)(nil),         // 17: grpc_server.GatewayServerConfig
	(*MiddlewareStatus)(nil),            // 18: grpc_server.MiddlewareStatus
	nil,                                 // 19: grpc_server.DomainMapResponse.DomainsMapEntry
	nil,                                 // 20: grpc_server.DomainMapResponse.DomainFrontMapEntry
}
var file_app_grpc_service_proto_depIdxs = []int32{
	2,  // 0: grpc_server.GatewayStatusResponse.servers:type_name -> grpc_server.ServerStatus
	2,  // 1: grpc_server.GatewayStatusResponse.http3_servers:type_name -> grpc_server.ServerStatus
	17, // 2: grpc_server.GatewayStatusResponse.server_configs:type_name -> grpc_server.GatewayServerConfig
	18, // 3: grpc_server.GatewayStatusResponse.middleware:type_name -> grpc_server.MiddlewareStatus
	5,  // 4: grpc_server.ModifierManagerInfoResponse.modifiers:type_name -> grpc_server.ModifierInfo
	19, // 5: grpc_server.DomainMapResponse.domains_map:type_name -> grpc_server.DomainMapResponse.DomainsMapEntry
	20, // 6: grpc_server.DomainMapResponse.domain_front_map:type_name -> grpc_server.DomainMapResponse.DomainFrontMapEntry
	11, // 7: grpc_server.DomainPortsResponse.ports:type_name -> grpc_server.DomainPorts
	9,  // 8: grpc_server.DomainMapResponse.DomainsMapEntry.value:type_name -> grpc_server.ServiceMap
	0,  // 9: grpc_server.AppService.GetGatewayStatus:input_type -> grpc_server.Empty
	0,  // 10: grpc_server.AppService.GetFrontProxyStatus:input_type -> grpc_server.Empty
	0,  // 11: grpc_server.AppService.GetModifierManagerInfo:input_type -> grpc_server.Empty
	0,  // 12: grpc_server.AppService.GetStatServerConfig:input_type -> grpc_server.Empty
	0,  // 13: grpc_server.AppService.GetRuntime:input_type -> grpc_server.Empty
	0,  // 14: grpc_server.AppService.GetDomainMap:input_type -> grpc_server.Empty
	0,  // 15: grpc_server.AppService.GetDomainPorts:input_type -> grpc_server.Empty
	12, // 16: grpc_server.AppService.ReloadConfig:input_type -> grpc_server.ReloadConfigRequest
	0,  // 17: grpc_server.AppService.ReStartFrontServer:input_type -> grpc_server.Empty
	0,  // 18: grpc_server.AppService.ReStartGateway:input_type -> grpc_server.Empty
	0,  // 19: grpc_server.AppService.ReStartAPIServer:input_type -> grpc_server.Empty
	0,  // 20: grpc_server.AppService.ReStartBackendServer:input_type -> grpc_server.Empty
	0,  // 21: grpc_server.AppService.ReStartLatencyServer:input_type -> grpc_server.Empty
	0,  // 22: grpc_server.AppService.ReStartVPNServer:input_type -> grpc_server.Empty
	0,  // 23: grpc_server.AppService.ReStartTrojanServer:input_type -> grpc_server.Empty
	0,  // 24: grpc_server.AppService.ReStartAnyTLSServer:input_type -> grpc_server.Empty
	15, // 25: grpc_server.AppService.StartDomainService:input_type -> grpc_server.DomainServiceRequest
	15, // 26: grpc_server.AppService.StopDomainService:input_type -> grpc_server.DomainServiceRequest
	14, // 27: grpc_server.AppService.DumpRuntime:input_type -> grpc_server.DumpRuntimeRequest
	1,  // 28: grpc_server.AppService.GetGatewayStatus:output_type -> grpc_server.GatewayStatusResponse
	3,  // 29: grpc_server.AppService.GetFrontProxyStatus:output_type -> grpc_server.FrontProxyStatusResponse
	4,  // 30: grpc_server.AppService.GetModifierManagerInfo:output_type -> grpc_server.ModifierManagerInfoResponse
	6,  // 31: grpc_server.AppService.GetStatServerConfig:output_type -> grpc_server.StatServerConfigResponse
	7,  // 32: grpc_server.AppService.GetRuntime:output_type -> grpc_server.RuntimeResponse
	8,  // 33: grpc_server.AppService.GetDomainMap:output_type -> grpc_server.DomainMapResponse
	10, // 34: grpc_server.AppService.GetDomainPorts:output_type -> grpc_server.DomainPortsResponse
	13, // 35: grpc_server.AppService.ReloadConfig:output_type -> grpc_server.ReloadConfigResponse
	16, // 36: grpc_server.AppService.ReStartFrontServer:output_type -> grpc_server.ActionResponse
	16, // 37: grpc_server.AppService.ReStartGateway:output_type -> grpc_server.ActionResponse
	16, // 38: grpc_server.AppService.ReStartAPIServer:output_type -> grpc_server.ActionResponse
	16, // 39: grpc_server.AppService.ReStartBackendServer:output_type -> grpc_server.ActionResponse
	16, // 40: grpc_server.AppService.ReStartLatencyServer:output_type -> grpc_server.ActionResponse
	16, // 41: grpc_server.AppService.ReStartVPNServer:output_type -> grpc_server.ActionResponse
	16, // 42: grpc_server.AppService.ReStartTrojanServer:output_type -> grpc_server.ActionResponse
	16, // 43: grpc_server.AppService.ReStartAnyTLSServer:output_type -> grpc_server.ActionResponse
	16, // 44: grpc_server.AppService.StartDomainService:output_type -> grpc_server.ActionResponse
	16, // 45: grpc_server.AppService.StopDomainService:output_type -> grpc_server.ActionResponse
	16, // 46: grpc_server.AppService.DumpRuntime:output_type -> grpc_server.ActionResponse
	28, // [28:47] is the sub-list for method output_type
	9,  // [9:28] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_app_grpc_service_proto_init() }
func file_app_grpc_service_proto_init() {
	if File_app_grpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_grpc_service_proto_rawDesc), len(file_app_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_service_proto_goTypes,
		DependencyIndexes: file_app_grpc_service_proto_depIdxs,
		MessageInfos:      file_app_grpc_service_proto_msgTypes,
	}.Build()
	File_app_grpc_service_proto = out.File
	file_app_grpc_service_proto_goTypes = nil
	file_app_grpc_service_proto_depIdxs = nil
}
