// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: app/grpc/service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppService_GetGatewayStatus_FullMethodName       = "/grpc_server.AppService/GetGatewayStatus"
	AppService_GetFrontProxyStatus_FullMethodName    = "/grpc_server.AppService/GetFrontProxyStatus"
	AppService_GetModifierManagerInfo_FullMethodName = "/grpc_server.AppService/GetModifierManagerInfo"
	AppService_GetStatServerConfig_FullMethodName    = "/grpc_server.AppService/GetStatServerConfig"
	AppService_GetRuntime_FullMethodName             = "/grpc_server.AppService/GetRuntime"
	AppService_GetDomainMap_FullMethodName           = "/grpc_server.AppService/GetDomainMap"
	AppService_GetDomainPorts_FullMethodName         = "/grpc_server.AppService/GetDomainPorts"
	AppService_ReloadConfig_FullMethodName           = "/grpc_server.AppService/ReloadConfig"
	AppService_ReStartFrontServer_FullMethodName     = "/grpc_server.AppService/ReStartFrontServer"
	AppService_ReStartGateway_FullMethodName         = "/grpc_server.AppService/ReStartGateway"
	AppService_ReStartAPIServer_FullMethodName       = "/grpc_server.AppService/ReStartAPIServer"
	AppService_ReStartBackendServer_FullMethodName   = "/grpc_server.AppService/ReStartBackendServer"
	AppService_ReStartLatencyServer_FullMethodName   = "/grpc_server.AppService/ReStartLatencyServer"
	AppService_ReStartVPNServer_FullMethodName       = "/grpc_server.AppService/ReStartVPNServer"
	AppService_ReStartTrojanServer_FullMethodName    = "/grpc_server.AppService/ReStartTrojanServer"
	AppService_ReStartAnyTLSServer_FullMethodName    = "/grpc_server.AppService/ReStartAnyTLSServer"
	AppService_StartDomainService_FullMethodName     = "/grpc_server.AppService/StartDomainService"
	AppService_StopDomainService_FullMethodName      = "/grpc_server.AppService/StopDomainService"
	AppService_DumpRuntime_FullMethodName            = "/grpc_server.AppService/DumpRuntime"
)

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppServiceClient interface {
	// 获取Gateway状态
	GetGatewayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GatewayStatusResponse, error)
	// 获取FrontProxy状态
	GetFrontProxyStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FrontProxyStatusResponse, error)
	// 获取ModifierManager信息
	GetModifierManagerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModifierManagerInfoResponse, error)
	// 获取StatServer配置
	GetStatServerConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatServerConfigResponse, error)
	// 获取运行时信息
	GetRuntime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RuntimeResponse, error)
	// 获取域名映射数据
	GetDomainMap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainMapResponse, error)
	// 获取域名端口数据
	GetDomainPorts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainPortsResponse, error)
	// 重新加载配置
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error)
	// 重启前端服务器
	ReStartFrontServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启网关服务器
	ReStartGateway(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启API服务器
	ReStartAPIServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启Backend服务器
	ReStartBackendServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启Latency服务器
	ReStartLatencyServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启VPN服务器
	ReStartVPNServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启Trojan服务器
	ReStartTrojanServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 重启AnyTLS服务器
	ReStartAnyTLSServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// 启动域名服务
	StartDomainService(ctx context.Context, in *DomainServiceRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// 停止域名服务
	StopDomainService(ctx context.Context, in *DomainServiceRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Dump运行时到文件
	DumpRuntime(ctx context.Context, in *DumpRuntimeRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type appServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppServiceClient(cc grpc.ClientConnInterface) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) GetGatewayStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GatewayStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayStatusResponse)
	err := c.cc.Invoke(ctx, AppService_GetGatewayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetFrontProxyStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FrontProxyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrontProxyStatusResponse)
	err := c.cc.Invoke(ctx, AppService_GetFrontProxyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetModifierManagerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModifierManagerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifierManagerInfoResponse)
	err := c.cc.Invoke(ctx, AppService_GetModifierManagerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetStatServerConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatServerConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatServerConfigResponse)
	err := c.cc.Invoke(ctx, AppService_GetStatServerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetRuntime(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, AppService_GetRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetDomainMap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainMapResponse)
	err := c.cc.Invoke(ctx, AppService_GetDomainMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetDomainPorts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DomainPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainPortsResponse)
	err := c.cc.Invoke(ctx, AppService_GetDomainPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ReloadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadConfigResponse)
	err := c.cc.Invoke(ctx, AppService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartFrontServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartFrontServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartGateway(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartAPIServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartAPIServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartBackendServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartBackendServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartLatencyServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartLatencyServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartVPNServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartVPNServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartTrojanServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartTrojanServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ReStartAnyTLSServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_ReStartAnyTLSServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) StartDomainService(ctx context.Context, in *DomainServiceRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_StartDomainService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) StopDomainService(ctx context.Context, in *DomainServiceRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_StopDomainService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DumpRuntime(ctx context.Context, in *DumpRuntimeRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, AppService_DumpRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
// All implementations must embed UnimplementedAppServiceServer
// for forward compatibility.
type AppServiceServer interface {
	// 获取Gateway状态
	GetGatewayStatus(context.Context, *Empty) (*GatewayStatusResponse, error)
	// 获取FrontProxy状态
	GetFrontProxyStatus(context.Context, *Empty) (*FrontProxyStatusResponse, error)
	// 获取ModifierManager信息
	GetModifierManagerInfo(context.Context, *Empty) (*ModifierManagerInfoResponse, error)
	// 获取StatServer配置
	GetStatServerConfig(context.Context, *Empty) (*StatServerConfigResponse, error)
	// 获取运行时信息
	GetRuntime(context.Context, *Empty) (*RuntimeResponse, error)
	// 获取域名映射数据
	GetDomainMap(context.Context, *Empty) (*DomainMapResponse, error)
	// 获取域名端口数据
	GetDomainPorts(context.Context, *Empty) (*DomainPortsResponse, error)
	// 重新加载配置
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error)
	// 重启前端服务器
	ReStartFrontServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启网关服务器
	ReStartGateway(context.Context, *Empty) (*ActionResponse, error)
	// 重启API服务器
	ReStartAPIServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启Backend服务器
	ReStartBackendServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启Latency服务器
	ReStartLatencyServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启VPN服务器
	ReStartVPNServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启Trojan服务器
	ReStartTrojanServer(context.Context, *Empty) (*ActionResponse, error)
	// 重启AnyTLS服务器
	ReStartAnyTLSServer(context.Context, *Empty) (*ActionResponse, error)
	// 启动域名服务
	StartDomainService(context.Context, *DomainServiceRequest) (*ActionResponse, error)
	// 停止域名服务
	StopDomainService(context.Context, *DomainServiceRequest) (*ActionResponse, error)
	// Dump运行时到文件
	DumpRuntime(context.Context, *DumpRuntimeRequest) (*ActionResponse, error)
	mustEmbedUnimplementedAppServiceServer()
}

// UnimplementedAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServiceServer struct{}

func (UnimplementedAppServiceServer) GetGatewayStatus(context.Context, *Empty) (*GatewayStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayStatus not implemented")
}
func (UnimplementedAppServiceServer) GetFrontProxyStatus(context.Context, *Empty) (*FrontProxyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrontProxyStatus not implemented")
}
func (UnimplementedAppServiceServer) GetModifierManagerInfo(context.Context, *Empty) (*ModifierManagerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModifierManagerInfo not implemented")
}
func (UnimplementedAppServiceServer) GetStatServerConfig(context.Context, *Empty) (*StatServerConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatServerConfig not implemented")
}
func (UnimplementedAppServiceServer) GetRuntime(context.Context, *Empty) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntime not implemented")
}
func (UnimplementedAppServiceServer) GetDomainMap(context.Context, *Empty) (*DomainMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainMap not implemented")
}
func (UnimplementedAppServiceServer) GetDomainPorts(context.Context, *Empty) (*DomainPortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainPorts not implemented")
}
func (UnimplementedAppServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ReloadConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedAppServiceServer) ReStartFrontServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartFrontServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartGateway(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartGateway not implemented")
}
func (UnimplementedAppServiceServer) ReStartAPIServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartAPIServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartBackendServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartBackendServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartLatencyServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartLatencyServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartVPNServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartVPNServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartTrojanServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartTrojanServer not implemented")
}
func (UnimplementedAppServiceServer) ReStartAnyTLSServer(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReStartAnyTLSServer not implemented")
}
func (UnimplementedAppServiceServer) StartDomainService(context.Context, *DomainServiceRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDomainService not implemented")
}
func (UnimplementedAppServiceServer) StopDomainService(context.Context, *DomainServiceRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDomainService not implemented")
}
func (UnimplementedAppServiceServer) DumpRuntime(context.Context, *DumpRuntimeRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpRuntime not implemented")
}
func (UnimplementedAppServiceServer) mustEmbedUnimplementedAppServiceServer() {}
func (UnimplementedAppServiceServer) testEmbeddedByValue()                    {}

// UnsafeAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServiceServer will
// result in compilation errors.
type UnsafeAppServiceServer interface {
	mustEmbedUnimplementedAppServiceServer()
}

func RegisterAppServiceServer(s grpc.ServiceRegistrar, srv AppServiceServer) {
	// If the following call pancis, it indicates UnimplementedAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppService_ServiceDesc, srv)
}

func _AppService_GetGatewayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetGatewayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetGatewayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetGatewayStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetFrontProxyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetFrontProxyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetFrontProxyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetFrontProxyStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetModifierManagerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetModifierManagerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetModifierManagerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetModifierManagerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetStatServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetStatServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetStatServerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetStatServerConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetRuntime(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetDomainMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetDomainMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetDomainMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetDomainMap(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetDomainPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetDomainPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_GetDomainPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetDomainPorts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartFrontServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartFrontServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartFrontServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartFrontServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartGateway(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartAPIServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartAPIServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartAPIServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartAPIServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartBackendServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartBackendServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartBackendServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartBackendServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartLatencyServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartLatencyServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartLatencyServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartLatencyServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartVPNServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartVPNServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartVPNServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartVPNServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartTrojanServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartTrojanServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartTrojanServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartTrojanServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ReStartAnyTLSServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ReStartAnyTLSServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_ReStartAnyTLSServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ReStartAnyTLSServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_StartDomainService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).StartDomainService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_StartDomainService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).StartDomainService(ctx, req.(*DomainServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_StopDomainService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).StopDomainService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_StopDomainService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).StopDomainService(ctx, req.(*DomainServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DumpRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DumpRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppService_DumpRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DumpRuntime(ctx, req.(*DumpRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppService_ServiceDesc is the grpc.ServiceDesc for AppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_server.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayStatus",
			Handler:    _AppService_GetGatewayStatus_Handler,
		},
		{
			MethodName: "GetFrontProxyStatus",
			Handler:    _AppService_GetFrontProxyStatus_Handler,
		},
		{
			MethodName: "GetModifierManagerInfo",
			Handler:    _AppService_GetModifierManagerInfo_Handler,
		},
		{
			MethodName: "GetStatServerConfig",
			Handler:    _AppService_GetStatServerConfig_Handler,
		},
		{
			MethodName: "GetRuntime",
			Handler:    _AppService_GetRuntime_Handler,
		},
		{
			MethodName: "GetDomainMap",
			Handler:    _AppService_GetDomainMap_Handler,
		},
		{
			MethodName: "GetDomainPorts",
			Handler:    _AppService_GetDomainPorts_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _AppService_ReloadConfig_Handler,
		},
		{
			MethodName: "ReStartFrontServer",
			Handler:    _AppService_ReStartFrontServer_Handler,
		},
		{
			MethodName: "ReStartGateway",
			Handler:    _AppService_ReStartGateway_Handler,
		},
		{
			MethodName: "ReStartAPIServer",
			Handler:    _AppService_ReStartAPIServer_Handler,
		},
		{
			MethodName: "ReStartBackendServer",
			Handler:    _AppService_ReStartBackendServer_Handler,
		},
		{
			MethodName: "ReStartLatencyServer",
			Handler:    _AppService_ReStartLatencyServer_Handler,
		},
		{
			MethodName: "ReStartVPNServer",
			Handler:    _AppService_ReStartVPNServer_Handler,
		},
		{
			MethodName: "ReStartTrojanServer",
			Handler:    _AppService_ReStartTrojanServer_Handler,
		},
		{
			MethodName: "ReStartAnyTLSServer",
			Handler:    _AppService_ReStartAnyTLSServer_Handler,
		},
		{
			MethodName: "StartDomainService",
			Handler:    _AppService_StartDomainService_Handler,
		},
		{
			MethodName: "StopDomainService",
			Handler:    _AppService_StopDomainService_Handler,
		},
		{
			MethodName: "DumpRuntime",
			Handler:    _AppService_DumpRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/grpc/service.proto",
}
