// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: hamburger.proto

package connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// serviceName is the fully-qualified name of the service service.
	serviceName = "hamburger.service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceStatProcedure is the fully-qualified name of the service's stat RPC.
	ServiceStatProcedure = "/hamburger.service/stat"
	// ServiceGeoProcedure is the fully-qualified name of the service's geo RPC.
	ServiceGeoProcedure = "/hamburger.service/geo"
	// ServiceDomainProcedure is the fully-qualified name of the service's domain RPC.
	ServiceDomainProcedure = "/hamburger.service/domain"
	// ServiceConnProcedure is the fully-qualified name of the service's conn RPC.
	ServiceConnProcedure = "/hamburger.service/conn"
	// ServiceHealthProcedure is the fully-qualified name of the service's health RPC.
	ServiceHealthProcedure = "/hamburger.service/health"
	// ServiceLoginProcedure is the fully-qualified name of the service's login RPC.
	ServiceLoginProcedure = "/hamburger.service/login"
	// ServiceLogoutProcedure is the fully-qualified name of the service's logout RPC.
	ServiceLogoutProcedure = "/hamburger.service/logout"
	// ServiceUserGetProcedure is the fully-qualified name of the service's userGet RPC.
	ServiceUserGetProcedure = "/hamburger.service/userGet"
	// ServiceUserUpdateProcedure is the fully-qualified name of the service's userUpdate RPC.
	ServiceUserUpdateProcedure = "/hamburger.service/userUpdate"
	// ServiceUserCreateProcedure is the fully-qualified name of the service's userCreate RPC.
	ServiceUserCreateProcedure = "/hamburger.service/userCreate"
	// ServiceUserDeleteProcedure is the fully-qualified name of the service's userDelete RPC.
	ServiceUserDeleteProcedure = "/hamburger.service/userDelete"
	// ServiceServiceStartProcedure is the fully-qualified name of the service's serviceStart RPC.
	ServiceServiceStartProcedure = "/hamburger.service/serviceStart"
	// ServiceServiceStopProcedure is the fully-qualified name of the service's serviceStop RPC.
	ServiceServiceStopProcedure = "/hamburger.service/serviceStop"
	// ServiceServerRestartProcedure is the fully-qualified name of the service's serverRestart RPC.
	ServiceServerRestartProcedure = "/hamburger.service/serverRestart"
	// ServiceServerStopProcedure is the fully-qualified name of the service's serverStop RPC.
	ServiceServerStopProcedure = "/hamburger.service/serverStop"
	// ServiceStatStreamProcedure is the fully-qualified name of the service's statStream RPC.
	ServiceStatStreamProcedure = "/hamburger.service/statStream"
	// ServiceGeoStreamProcedure is the fully-qualified name of the service's geoStream RPC.
	ServiceGeoStreamProcedure = "/hamburger.service/geoStream"
	// ServiceDomainStreamProcedure is the fully-qualified name of the service's domainStream RPC.
	ServiceDomainStreamProcedure = "/hamburger.service/domainStream"
	// ServiceConnStreamProcedure is the fully-qualified name of the service's connStream RPC.
	ServiceConnStreamProcedure = "/hamburger.service/connStream"
	// ServiceHealthStreamProcedure is the fully-qualified name of the service's healthStream RPC.
	ServiceHealthStreamProcedure = "/hamburger.service/healthStream"
	// ServiceLoginStreamProcedure is the fully-qualified name of the service's loginStream RPC.
	ServiceLoginStreamProcedure = "/hamburger.service/loginStream"
	// ServiceLogoutStreamProcedure is the fully-qualified name of the service's logoutStream RPC.
	ServiceLogoutStreamProcedure = "/hamburger.service/logoutStream"
	// ServiceUserGetStreamProcedure is the fully-qualified name of the service's userGetStream RPC.
	ServiceUserGetStreamProcedure = "/hamburger.service/userGetStream"
	// ServiceUserUpdateStreamProcedure is the fully-qualified name of the service's userUpdateStream
	// RPC.
	ServiceUserUpdateStreamProcedure = "/hamburger.service/userUpdateStream"
	// ServiceUserCreateStreamProcedure is the fully-qualified name of the service's userCreateStream
	// RPC.
	ServiceUserCreateStreamProcedure = "/hamburger.service/userCreateStream"
	// ServiceUserDeleteStreamProcedure is the fully-qualified name of the service's userDeleteStream
	// RPC.
	ServiceUserDeleteStreamProcedure = "/hamburger.service/userDeleteStream"
	// ServiceServiceStartStreamProcedure is the fully-qualified name of the service's
	// serviceStartStream RPC.
	ServiceServiceStartStreamProcedure = "/hamburger.service/serviceStartStream"
	// ServiceServiceStopStreamProcedure is the fully-qualified name of the service's serviceStopStream
	// RPC.
	ServiceServiceStopStreamProcedure = "/hamburger.service/serviceStopStream"
	// ServiceServerRestartStreamProcedure is the fully-qualified name of the service's
	// serverRestartStream RPC.
	ServiceServerRestartStreamProcedure = "/hamburger.service/serverRestartStream"
	// ServiceServerStopStreamProcedure is the fully-qualified name of the service's serverStopStream
	// RPC.
	ServiceServerStopStreamProcedure = "/hamburger.service/serverStopStream"
)

// ServiceClient is a client for the hamburger.service service.
type ServiceClient interface {
	Stat(context.Context, *connect.Request[StatRequest]) (*connect.Response[StatResponse], error)
	Geo(context.Context, *connect.Request[Empty]) (*connect.Response[GeoResponse], error)
	Domain(context.Context, *connect.Request[Empty]) (*connect.Response[DomainResponse], error)
	Conn(context.Context, *connect.Request[Empty]) (*connect.Response[ConnResponse], error)
	Health(context.Context, *connect.Request[Empty]) (*connect.Response[HealthResponse], error)
	Login(context.Context, *connect.Request[LoginRequest]) (*connect.Response[LoginResponse], error)
	Logout(context.Context, *connect.Request[Empty]) (*connect.Response[ActionResponse], error)
	UserGet(context.Context, *connect.Request[Empty]) (*connect.Response[UserResponse], error)
	UserUpdate(context.Context, *connect.Request[UserUpdateRequest]) (*connect.Response[UserResponse], error)
	UserCreate(context.Context, *connect.Request[UserCreateRequest]) (*connect.Response[UserResponse], error)
	UserDelete(context.Context, *connect.Request[UserDeleteRequest]) (*connect.Response[ActionResponse], error)
	ServiceStart(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error)
	ServiceStop(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error)
	ServerRestart(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error)
	ServerStop(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error)
	StatStream(context.Context) *connect.BidiStreamForClient[StatRequest, StatResponse]
	GeoStream(context.Context) *connect.BidiStreamForClient[Empty, GeoResponse]
	DomainStream(context.Context) *connect.BidiStreamForClient[Empty, DomainResponse]
	ConnStream(context.Context) *connect.BidiStreamForClient[Empty, ConnResponse]
	HealthStream(context.Context) *connect.BidiStreamForClient[Empty, HealthResponse]
	LoginStream(context.Context) *connect.BidiStreamForClient[LoginRequest, LoginResponse]
	LogoutStream(context.Context) *connect.BidiStreamForClient[Empty, ActionResponse]
	UserGetStream(context.Context) *connect.BidiStreamForClient[Empty, UserResponse]
	UserUpdateStream(context.Context) *connect.BidiStreamForClient[UserUpdateRequest, UserResponse]
	UserCreateStream(context.Context) *connect.BidiStreamForClient[UserCreateRequest, UserResponse]
	UserDeleteStream(context.Context) *connect.BidiStreamForClient[UserDeleteRequest, ActionResponse]
	ServiceStartStream(context.Context) *connect.BidiStreamForClient[DomainServiceRequest, ActionResponse]
	ServiceStopStream(context.Context) *connect.BidiStreamForClient[DomainServiceRequest, ActionResponse]
	ServerRestartStream(context.Context) *connect.BidiStreamForClient[ServerRequest, ActionResponse]
	ServerStopStream(context.Context) *connect.BidiStreamForClient[ServerRequest, ActionResponse]
}

// NewServiceClient constructs a client for the hamburger.service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := File_hamburger_proto.Services().ByName("service").Methods()
	return &serviceClient{
		stat: connect.NewClient[StatRequest, StatResponse](
			httpClient,
			baseURL+ServiceStatProcedure,
			connect.WithSchema(serviceMethods.ByName("stat")),
			connect.WithClientOptions(opts...),
		),
		geo: connect.NewClient[Empty, GeoResponse](
			httpClient,
			baseURL+ServiceGeoProcedure,
			connect.WithSchema(serviceMethods.ByName("geo")),
			connect.WithClientOptions(opts...),
		),
		domain: connect.NewClient[Empty, DomainResponse](
			httpClient,
			baseURL+ServiceDomainProcedure,
			connect.WithSchema(serviceMethods.ByName("domain")),
			connect.WithClientOptions(opts...),
		),
		conn: connect.NewClient[Empty, ConnResponse](
			httpClient,
			baseURL+ServiceConnProcedure,
			connect.WithSchema(serviceMethods.ByName("conn")),
			connect.WithClientOptions(opts...),
		),
		health: connect.NewClient[Empty, HealthResponse](
			httpClient,
			baseURL+ServiceHealthProcedure,
			connect.WithSchema(serviceMethods.ByName("health")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[LoginRequest, LoginResponse](
			httpClient,
			baseURL+ServiceLoginProcedure,
			connect.WithSchema(serviceMethods.ByName("login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[Empty, ActionResponse](
			httpClient,
			baseURL+ServiceLogoutProcedure,
			connect.WithSchema(serviceMethods.ByName("logout")),
			connect.WithClientOptions(opts...),
		),
		userGet: connect.NewClient[Empty, UserResponse](
			httpClient,
			baseURL+ServiceUserGetProcedure,
			connect.WithSchema(serviceMethods.ByName("userGet")),
			connect.WithClientOptions(opts...),
		),
		userUpdate: connect.NewClient[UserUpdateRequest, UserResponse](
			httpClient,
			baseURL+ServiceUserUpdateProcedure,
			connect.WithSchema(serviceMethods.ByName("userUpdate")),
			connect.WithClientOptions(opts...),
		),
		userCreate: connect.NewClient[UserCreateRequest, UserResponse](
			httpClient,
			baseURL+ServiceUserCreateProcedure,
			connect.WithSchema(serviceMethods.ByName("userCreate")),
			connect.WithClientOptions(opts...),
		),
		userDelete: connect.NewClient[UserDeleteRequest, ActionResponse](
			httpClient,
			baseURL+ServiceUserDeleteProcedure,
			connect.WithSchema(serviceMethods.ByName("userDelete")),
			connect.WithClientOptions(opts...),
		),
		serviceStart: connect.NewClient[DomainServiceRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServiceStartProcedure,
			connect.WithSchema(serviceMethods.ByName("serviceStart")),
			connect.WithClientOptions(opts...),
		),
		serviceStop: connect.NewClient[DomainServiceRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServiceStopProcedure,
			connect.WithSchema(serviceMethods.ByName("serviceStop")),
			connect.WithClientOptions(opts...),
		),
		serverRestart: connect.NewClient[ServerRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServerRestartProcedure,
			connect.WithSchema(serviceMethods.ByName("serverRestart")),
			connect.WithClientOptions(opts...),
		),
		serverStop: connect.NewClient[ServerRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServerStopProcedure,
			connect.WithSchema(serviceMethods.ByName("serverStop")),
			connect.WithClientOptions(opts...),
		),
		statStream: connect.NewClient[StatRequest, StatResponse](
			httpClient,
			baseURL+ServiceStatStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("statStream")),
			connect.WithClientOptions(opts...),
		),
		geoStream: connect.NewClient[Empty, GeoResponse](
			httpClient,
			baseURL+ServiceGeoStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("geoStream")),
			connect.WithClientOptions(opts...),
		),
		domainStream: connect.NewClient[Empty, DomainResponse](
			httpClient,
			baseURL+ServiceDomainStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("domainStream")),
			connect.WithClientOptions(opts...),
		),
		connStream: connect.NewClient[Empty, ConnResponse](
			httpClient,
			baseURL+ServiceConnStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("connStream")),
			connect.WithClientOptions(opts...),
		),
		healthStream: connect.NewClient[Empty, HealthResponse](
			httpClient,
			baseURL+ServiceHealthStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("healthStream")),
			connect.WithClientOptions(opts...),
		),
		loginStream: connect.NewClient[LoginRequest, LoginResponse](
			httpClient,
			baseURL+ServiceLoginStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("loginStream")),
			connect.WithClientOptions(opts...),
		),
		logoutStream: connect.NewClient[Empty, ActionResponse](
			httpClient,
			baseURL+ServiceLogoutStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("logoutStream")),
			connect.WithClientOptions(opts...),
		),
		userGetStream: connect.NewClient[Empty, UserResponse](
			httpClient,
			baseURL+ServiceUserGetStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("userGetStream")),
			connect.WithClientOptions(opts...),
		),
		userUpdateStream: connect.NewClient[UserUpdateRequest, UserResponse](
			httpClient,
			baseURL+ServiceUserUpdateStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("userUpdateStream")),
			connect.WithClientOptions(opts...),
		),
		userCreateStream: connect.NewClient[UserCreateRequest, UserResponse](
			httpClient,
			baseURL+ServiceUserCreateStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("userCreateStream")),
			connect.WithClientOptions(opts...),
		),
		userDeleteStream: connect.NewClient[UserDeleteRequest, ActionResponse](
			httpClient,
			baseURL+ServiceUserDeleteStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("userDeleteStream")),
			connect.WithClientOptions(opts...),
		),
		serviceStartStream: connect.NewClient[DomainServiceRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServiceStartStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("serviceStartStream")),
			connect.WithClientOptions(opts...),
		),
		serviceStopStream: connect.NewClient[DomainServiceRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServiceStopStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("serviceStopStream")),
			connect.WithClientOptions(opts...),
		),
		serverRestartStream: connect.NewClient[ServerRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServerRestartStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("serverRestartStream")),
			connect.WithClientOptions(opts...),
		),
		serverStopStream: connect.NewClient[ServerRequest, ActionResponse](
			httpClient,
			baseURL+ServiceServerStopStreamProcedure,
			connect.WithSchema(serviceMethods.ByName("serverStopStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	stat                *connect.Client[StatRequest, StatResponse]
	geo                 *connect.Client[Empty, GeoResponse]
	domain              *connect.Client[Empty, DomainResponse]
	conn                *connect.Client[Empty, ConnResponse]
	health              *connect.Client[Empty, HealthResponse]
	login               *connect.Client[LoginRequest, LoginResponse]
	logout              *connect.Client[Empty, ActionResponse]
	userGet             *connect.Client[Empty, UserResponse]
	userUpdate          *connect.Client[UserUpdateRequest, UserResponse]
	userCreate          *connect.Client[UserCreateRequest, UserResponse]
	userDelete          *connect.Client[UserDeleteRequest, ActionResponse]
	serviceStart        *connect.Client[DomainServiceRequest, ActionResponse]
	serviceStop         *connect.Client[DomainServiceRequest, ActionResponse]
	serverRestart       *connect.Client[ServerRequest, ActionResponse]
	serverStop          *connect.Client[ServerRequest, ActionResponse]
	statStream          *connect.Client[StatRequest, StatResponse]
	geoStream           *connect.Client[Empty, GeoResponse]
	domainStream        *connect.Client[Empty, DomainResponse]
	connStream          *connect.Client[Empty, ConnResponse]
	healthStream        *connect.Client[Empty, HealthResponse]
	loginStream         *connect.Client[LoginRequest, LoginResponse]
	logoutStream        *connect.Client[Empty, ActionResponse]
	userGetStream       *connect.Client[Empty, UserResponse]
	userUpdateStream    *connect.Client[UserUpdateRequest, UserResponse]
	userCreateStream    *connect.Client[UserCreateRequest, UserResponse]
	userDeleteStream    *connect.Client[UserDeleteRequest, ActionResponse]
	serviceStartStream  *connect.Client[DomainServiceRequest, ActionResponse]
	serviceStopStream   *connect.Client[DomainServiceRequest, ActionResponse]
	serverRestartStream *connect.Client[ServerRequest, ActionResponse]
	serverStopStream    *connect.Client[ServerRequest, ActionResponse]
}

// Stat calls hamburger.service.stat.
func (c *serviceClient) Stat(ctx context.Context, req *connect.Request[StatRequest]) (*connect.Response[StatResponse], error) {
	return c.stat.CallUnary(ctx, req)
}

// Geo calls hamburger.service.geo.
func (c *serviceClient) Geo(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[GeoResponse], error) {
	return c.geo.CallUnary(ctx, req)
}

// Domain calls hamburger.service.domain.
func (c *serviceClient) Domain(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[DomainResponse], error) {
	return c.domain.CallUnary(ctx, req)
}

// Conn calls hamburger.service.conn.
func (c *serviceClient) Conn(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[ConnResponse], error) {
	return c.conn.CallUnary(ctx, req)
}

// Health calls hamburger.service.health.
func (c *serviceClient) Health(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Login calls hamburger.service.login.
func (c *serviceClient) Login(ctx context.Context, req *connect.Request[LoginRequest]) (*connect.Response[LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls hamburger.service.logout.
func (c *serviceClient) Logout(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[ActionResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// UserGet calls hamburger.service.userGet.
func (c *serviceClient) UserGet(ctx context.Context, req *connect.Request[Empty]) (*connect.Response[UserResponse], error) {
	return c.userGet.CallUnary(ctx, req)
}

// UserUpdate calls hamburger.service.userUpdate.
func (c *serviceClient) UserUpdate(ctx context.Context, req *connect.Request[UserUpdateRequest]) (*connect.Response[UserResponse], error) {
	return c.userUpdate.CallUnary(ctx, req)
}

// UserCreate calls hamburger.service.userCreate.
func (c *serviceClient) UserCreate(ctx context.Context, req *connect.Request[UserCreateRequest]) (*connect.Response[UserResponse], error) {
	return c.userCreate.CallUnary(ctx, req)
}

// UserDelete calls hamburger.service.userDelete.
func (c *serviceClient) UserDelete(ctx context.Context, req *connect.Request[UserDeleteRequest]) (*connect.Response[ActionResponse], error) {
	return c.userDelete.CallUnary(ctx, req)
}

// ServiceStart calls hamburger.service.serviceStart.
func (c *serviceClient) ServiceStart(ctx context.Context, req *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error) {
	return c.serviceStart.CallUnary(ctx, req)
}

// ServiceStop calls hamburger.service.serviceStop.
func (c *serviceClient) ServiceStop(ctx context.Context, req *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error) {
	return c.serviceStop.CallUnary(ctx, req)
}

// ServerRestart calls hamburger.service.serverRestart.
func (c *serviceClient) ServerRestart(ctx context.Context, req *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error) {
	return c.serverRestart.CallUnary(ctx, req)
}

// ServerStop calls hamburger.service.serverStop.
func (c *serviceClient) ServerStop(ctx context.Context, req *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error) {
	return c.serverStop.CallUnary(ctx, req)
}

// StatStream calls hamburger.service.statStream.
func (c *serviceClient) StatStream(ctx context.Context) *connect.BidiStreamForClient[StatRequest, StatResponse] {
	return c.statStream.CallBidiStream(ctx)
}

// GeoStream calls hamburger.service.geoStream.
func (c *serviceClient) GeoStream(ctx context.Context) *connect.BidiStreamForClient[Empty, GeoResponse] {
	return c.geoStream.CallBidiStream(ctx)
}

// DomainStream calls hamburger.service.domainStream.
func (c *serviceClient) DomainStream(ctx context.Context) *connect.BidiStreamForClient[Empty, DomainResponse] {
	return c.domainStream.CallBidiStream(ctx)
}

// ConnStream calls hamburger.service.connStream.
func (c *serviceClient) ConnStream(ctx context.Context) *connect.BidiStreamForClient[Empty, ConnResponse] {
	return c.connStream.CallBidiStream(ctx)
}

// HealthStream calls hamburger.service.healthStream.
func (c *serviceClient) HealthStream(ctx context.Context) *connect.BidiStreamForClient[Empty, HealthResponse] {
	return c.healthStream.CallBidiStream(ctx)
}

// LoginStream calls hamburger.service.loginStream.
func (c *serviceClient) LoginStream(ctx context.Context) *connect.BidiStreamForClient[LoginRequest, LoginResponse] {
	return c.loginStream.CallBidiStream(ctx)
}

// LogoutStream calls hamburger.service.logoutStream.
func (c *serviceClient) LogoutStream(ctx context.Context) *connect.BidiStreamForClient[Empty, ActionResponse] {
	return c.logoutStream.CallBidiStream(ctx)
}

// UserGetStream calls hamburger.service.userGetStream.
func (c *serviceClient) UserGetStream(ctx context.Context) *connect.BidiStreamForClient[Empty, UserResponse] {
	return c.userGetStream.CallBidiStream(ctx)
}

// UserUpdateStream calls hamburger.service.userUpdateStream.
func (c *serviceClient) UserUpdateStream(ctx context.Context) *connect.BidiStreamForClient[UserUpdateRequest, UserResponse] {
	return c.userUpdateStream.CallBidiStream(ctx)
}

// UserCreateStream calls hamburger.service.userCreateStream.
func (c *serviceClient) UserCreateStream(ctx context.Context) *connect.BidiStreamForClient[UserCreateRequest, UserResponse] {
	return c.userCreateStream.CallBidiStream(ctx)
}

// UserDeleteStream calls hamburger.service.userDeleteStream.
func (c *serviceClient) UserDeleteStream(ctx context.Context) *connect.BidiStreamForClient[UserDeleteRequest, ActionResponse] {
	return c.userDeleteStream.CallBidiStream(ctx)
}

// ServiceStartStream calls hamburger.service.serviceStartStream.
func (c *serviceClient) ServiceStartStream(ctx context.Context) *connect.BidiStreamForClient[DomainServiceRequest, ActionResponse] {
	return c.serviceStartStream.CallBidiStream(ctx)
}

// ServiceStopStream calls hamburger.service.serviceStopStream.
func (c *serviceClient) ServiceStopStream(ctx context.Context) *connect.BidiStreamForClient[DomainServiceRequest, ActionResponse] {
	return c.serviceStopStream.CallBidiStream(ctx)
}

// ServerRestartStream calls hamburger.service.serverRestartStream.
func (c *serviceClient) ServerRestartStream(ctx context.Context) *connect.BidiStreamForClient[ServerRequest, ActionResponse] {
	return c.serverRestartStream.CallBidiStream(ctx)
}

// ServerStopStream calls hamburger.service.serverStopStream.
func (c *serviceClient) ServerStopStream(ctx context.Context) *connect.BidiStreamForClient[ServerRequest, ActionResponse] {
	return c.serverStopStream.CallBidiStream(ctx)
}

// ServiceHandler is an implementation of the hamburger.service service.
type ServiceHandler interface {
	Stat(context.Context, *connect.Request[StatRequest]) (*connect.Response[StatResponse], error)
	Geo(context.Context, *connect.Request[Empty]) (*connect.Response[GeoResponse], error)
	Domain(context.Context, *connect.Request[Empty]) (*connect.Response[DomainResponse], error)
	Conn(context.Context, *connect.Request[Empty]) (*connect.Response[ConnResponse], error)
	Health(context.Context, *connect.Request[Empty]) (*connect.Response[HealthResponse], error)
	Login(context.Context, *connect.Request[LoginRequest]) (*connect.Response[LoginResponse], error)
	Logout(context.Context, *connect.Request[Empty]) (*connect.Response[ActionResponse], error)
	UserGet(context.Context, *connect.Request[Empty]) (*connect.Response[UserResponse], error)
	UserUpdate(context.Context, *connect.Request[UserUpdateRequest]) (*connect.Response[UserResponse], error)
	UserCreate(context.Context, *connect.Request[UserCreateRequest]) (*connect.Response[UserResponse], error)
	UserDelete(context.Context, *connect.Request[UserDeleteRequest]) (*connect.Response[ActionResponse], error)
	ServiceStart(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error)
	ServiceStop(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error)
	ServerRestart(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error)
	ServerStop(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error)
	StatStream(context.Context, *connect.BidiStream[StatRequest, StatResponse]) error
	GeoStream(context.Context, *connect.BidiStream[Empty, GeoResponse]) error
	DomainStream(context.Context, *connect.BidiStream[Empty, DomainResponse]) error
	ConnStream(context.Context, *connect.BidiStream[Empty, ConnResponse]) error
	HealthStream(context.Context, *connect.BidiStream[Empty, HealthResponse]) error
	LoginStream(context.Context, *connect.BidiStream[LoginRequest, LoginResponse]) error
	LogoutStream(context.Context, *connect.BidiStream[Empty, ActionResponse]) error
	UserGetStream(context.Context, *connect.BidiStream[Empty, UserResponse]) error
	UserUpdateStream(context.Context, *connect.BidiStream[UserUpdateRequest, UserResponse]) error
	UserCreateStream(context.Context, *connect.BidiStream[UserCreateRequest, UserResponse]) error
	UserDeleteStream(context.Context, *connect.BidiStream[UserDeleteRequest, ActionResponse]) error
	ServiceStartStream(context.Context, *connect.BidiStream[DomainServiceRequest, ActionResponse]) error
	ServiceStopStream(context.Context, *connect.BidiStream[DomainServiceRequest, ActionResponse]) error
	ServerRestartStream(context.Context, *connect.BidiStream[ServerRequest, ActionResponse]) error
	ServerStopStream(context.Context, *connect.BidiStream[ServerRequest, ActionResponse]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := File_hamburger_proto.Services().ByName("service").Methods()
	serviceStatHandler := connect.NewUnaryHandler(
		ServiceStatProcedure,
		svc.Stat,
		connect.WithSchema(serviceMethods.ByName("stat")),
		connect.WithHandlerOptions(opts...),
	)
	serviceGeoHandler := connect.NewUnaryHandler(
		ServiceGeoProcedure,
		svc.Geo,
		connect.WithSchema(serviceMethods.ByName("geo")),
		connect.WithHandlerOptions(opts...),
	)
	serviceDomainHandler := connect.NewUnaryHandler(
		ServiceDomainProcedure,
		svc.Domain,
		connect.WithSchema(serviceMethods.ByName("domain")),
		connect.WithHandlerOptions(opts...),
	)
	serviceConnHandler := connect.NewUnaryHandler(
		ServiceConnProcedure,
		svc.Conn,
		connect.WithSchema(serviceMethods.ByName("conn")),
		connect.WithHandlerOptions(opts...),
	)
	serviceHealthHandler := connect.NewUnaryHandler(
		ServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(serviceMethods.ByName("health")),
		connect.WithHandlerOptions(opts...),
	)
	serviceLoginHandler := connect.NewUnaryHandler(
		ServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(serviceMethods.ByName("login")),
		connect.WithHandlerOptions(opts...),
	)
	serviceLogoutHandler := connect.NewUnaryHandler(
		ServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(serviceMethods.ByName("logout")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserGetHandler := connect.NewUnaryHandler(
		ServiceUserGetProcedure,
		svc.UserGet,
		connect.WithSchema(serviceMethods.ByName("userGet")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserUpdateHandler := connect.NewUnaryHandler(
		ServiceUserUpdateProcedure,
		svc.UserUpdate,
		connect.WithSchema(serviceMethods.ByName("userUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserCreateHandler := connect.NewUnaryHandler(
		ServiceUserCreateProcedure,
		svc.UserCreate,
		connect.WithSchema(serviceMethods.ByName("userCreate")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserDeleteHandler := connect.NewUnaryHandler(
		ServiceUserDeleteProcedure,
		svc.UserDelete,
		connect.WithSchema(serviceMethods.ByName("userDelete")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServiceStartHandler := connect.NewUnaryHandler(
		ServiceServiceStartProcedure,
		svc.ServiceStart,
		connect.WithSchema(serviceMethods.ByName("serviceStart")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServiceStopHandler := connect.NewUnaryHandler(
		ServiceServiceStopProcedure,
		svc.ServiceStop,
		connect.WithSchema(serviceMethods.ByName("serviceStop")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServerRestartHandler := connect.NewUnaryHandler(
		ServiceServerRestartProcedure,
		svc.ServerRestart,
		connect.WithSchema(serviceMethods.ByName("serverRestart")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServerStopHandler := connect.NewUnaryHandler(
		ServiceServerStopProcedure,
		svc.ServerStop,
		connect.WithSchema(serviceMethods.ByName("serverStop")),
		connect.WithHandlerOptions(opts...),
	)
	serviceStatStreamHandler := connect.NewBidiStreamHandler(
		ServiceStatStreamProcedure,
		svc.StatStream,
		connect.WithSchema(serviceMethods.ByName("statStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceGeoStreamHandler := connect.NewBidiStreamHandler(
		ServiceGeoStreamProcedure,
		svc.GeoStream,
		connect.WithSchema(serviceMethods.ByName("geoStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceDomainStreamHandler := connect.NewBidiStreamHandler(
		ServiceDomainStreamProcedure,
		svc.DomainStream,
		connect.WithSchema(serviceMethods.ByName("domainStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceConnStreamHandler := connect.NewBidiStreamHandler(
		ServiceConnStreamProcedure,
		svc.ConnStream,
		connect.WithSchema(serviceMethods.ByName("connStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceHealthStreamHandler := connect.NewBidiStreamHandler(
		ServiceHealthStreamProcedure,
		svc.HealthStream,
		connect.WithSchema(serviceMethods.ByName("healthStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceLoginStreamHandler := connect.NewBidiStreamHandler(
		ServiceLoginStreamProcedure,
		svc.LoginStream,
		connect.WithSchema(serviceMethods.ByName("loginStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceLogoutStreamHandler := connect.NewBidiStreamHandler(
		ServiceLogoutStreamProcedure,
		svc.LogoutStream,
		connect.WithSchema(serviceMethods.ByName("logoutStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserGetStreamHandler := connect.NewBidiStreamHandler(
		ServiceUserGetStreamProcedure,
		svc.UserGetStream,
		connect.WithSchema(serviceMethods.ByName("userGetStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserUpdateStreamHandler := connect.NewBidiStreamHandler(
		ServiceUserUpdateStreamProcedure,
		svc.UserUpdateStream,
		connect.WithSchema(serviceMethods.ByName("userUpdateStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserCreateStreamHandler := connect.NewBidiStreamHandler(
		ServiceUserCreateStreamProcedure,
		svc.UserCreateStream,
		connect.WithSchema(serviceMethods.ByName("userCreateStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceUserDeleteStreamHandler := connect.NewBidiStreamHandler(
		ServiceUserDeleteStreamProcedure,
		svc.UserDeleteStream,
		connect.WithSchema(serviceMethods.ByName("userDeleteStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServiceStartStreamHandler := connect.NewBidiStreamHandler(
		ServiceServiceStartStreamProcedure,
		svc.ServiceStartStream,
		connect.WithSchema(serviceMethods.ByName("serviceStartStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServiceStopStreamHandler := connect.NewBidiStreamHandler(
		ServiceServiceStopStreamProcedure,
		svc.ServiceStopStream,
		connect.WithSchema(serviceMethods.ByName("serviceStopStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServerRestartStreamHandler := connect.NewBidiStreamHandler(
		ServiceServerRestartStreamProcedure,
		svc.ServerRestartStream,
		connect.WithSchema(serviceMethods.ByName("serverRestartStream")),
		connect.WithHandlerOptions(opts...),
	)
	serviceServerStopStreamHandler := connect.NewBidiStreamHandler(
		ServiceServerStopStreamProcedure,
		svc.ServerStopStream,
		connect.WithSchema(serviceMethods.ByName("serverStopStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/hamburger.service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceStatProcedure:
			serviceStatHandler.ServeHTTP(w, r)
		case ServiceGeoProcedure:
			serviceGeoHandler.ServeHTTP(w, r)
		case ServiceDomainProcedure:
			serviceDomainHandler.ServeHTTP(w, r)
		case ServiceConnProcedure:
			serviceConnHandler.ServeHTTP(w, r)
		case ServiceHealthProcedure:
			serviceHealthHandler.ServeHTTP(w, r)
		case ServiceLoginProcedure:
			serviceLoginHandler.ServeHTTP(w, r)
		case ServiceLogoutProcedure:
			serviceLogoutHandler.ServeHTTP(w, r)
		case ServiceUserGetProcedure:
			serviceUserGetHandler.ServeHTTP(w, r)
		case ServiceUserUpdateProcedure:
			serviceUserUpdateHandler.ServeHTTP(w, r)
		case ServiceUserCreateProcedure:
			serviceUserCreateHandler.ServeHTTP(w, r)
		case ServiceUserDeleteProcedure:
			serviceUserDeleteHandler.ServeHTTP(w, r)
		case ServiceServiceStartProcedure:
			serviceServiceStartHandler.ServeHTTP(w, r)
		case ServiceServiceStopProcedure:
			serviceServiceStopHandler.ServeHTTP(w, r)
		case ServiceServerRestartProcedure:
			serviceServerRestartHandler.ServeHTTP(w, r)
		case ServiceServerStopProcedure:
			serviceServerStopHandler.ServeHTTP(w, r)
		case ServiceStatStreamProcedure:
			serviceStatStreamHandler.ServeHTTP(w, r)
		case ServiceGeoStreamProcedure:
			serviceGeoStreamHandler.ServeHTTP(w, r)
		case ServiceDomainStreamProcedure:
			serviceDomainStreamHandler.ServeHTTP(w, r)
		case ServiceConnStreamProcedure:
			serviceConnStreamHandler.ServeHTTP(w, r)
		case ServiceHealthStreamProcedure:
			serviceHealthStreamHandler.ServeHTTP(w, r)
		case ServiceLoginStreamProcedure:
			serviceLoginStreamHandler.ServeHTTP(w, r)
		case ServiceLogoutStreamProcedure:
			serviceLogoutStreamHandler.ServeHTTP(w, r)
		case ServiceUserGetStreamProcedure:
			serviceUserGetStreamHandler.ServeHTTP(w, r)
		case ServiceUserUpdateStreamProcedure:
			serviceUserUpdateStreamHandler.ServeHTTP(w, r)
		case ServiceUserCreateStreamProcedure:
			serviceUserCreateStreamHandler.ServeHTTP(w, r)
		case ServiceUserDeleteStreamProcedure:
			serviceUserDeleteStreamHandler.ServeHTTP(w, r)
		case ServiceServiceStartStreamProcedure:
			serviceServiceStartStreamHandler.ServeHTTP(w, r)
		case ServiceServiceStopStreamProcedure:
			serviceServiceStopStreamHandler.ServeHTTP(w, r)
		case ServiceServerRestartStreamProcedure:
			serviceServerRestartStreamHandler.ServeHTTP(w, r)
		case ServiceServerStopStreamProcedure:
			serviceServerStopStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Stat(context.Context, *connect.Request[StatRequest]) (*connect.Response[StatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.stat is not implemented"))
}

func (UnimplementedServiceHandler) Geo(context.Context, *connect.Request[Empty]) (*connect.Response[GeoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.geo is not implemented"))
}

func (UnimplementedServiceHandler) Domain(context.Context, *connect.Request[Empty]) (*connect.Response[DomainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.domain is not implemented"))
}

func (UnimplementedServiceHandler) Conn(context.Context, *connect.Request[Empty]) (*connect.Response[ConnResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.conn is not implemented"))
}

func (UnimplementedServiceHandler) Health(context.Context, *connect.Request[Empty]) (*connect.Response[HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.health is not implemented"))
}

func (UnimplementedServiceHandler) Login(context.Context, *connect.Request[LoginRequest]) (*connect.Response[LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.login is not implemented"))
}

func (UnimplementedServiceHandler) Logout(context.Context, *connect.Request[Empty]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.logout is not implemented"))
}

func (UnimplementedServiceHandler) UserGet(context.Context, *connect.Request[Empty]) (*connect.Response[UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userGet is not implemented"))
}

func (UnimplementedServiceHandler) UserUpdate(context.Context, *connect.Request[UserUpdateRequest]) (*connect.Response[UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userUpdate is not implemented"))
}

func (UnimplementedServiceHandler) UserCreate(context.Context, *connect.Request[UserCreateRequest]) (*connect.Response[UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userCreate is not implemented"))
}

func (UnimplementedServiceHandler) UserDelete(context.Context, *connect.Request[UserDeleteRequest]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userDelete is not implemented"))
}

func (UnimplementedServiceHandler) ServiceStart(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serviceStart is not implemented"))
}

func (UnimplementedServiceHandler) ServiceStop(context.Context, *connect.Request[DomainServiceRequest]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serviceStop is not implemented"))
}

func (UnimplementedServiceHandler) ServerRestart(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serverRestart is not implemented"))
}

func (UnimplementedServiceHandler) ServerStop(context.Context, *connect.Request[ServerRequest]) (*connect.Response[ActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serverStop is not implemented"))
}

func (UnimplementedServiceHandler) StatStream(context.Context, *connect.BidiStream[StatRequest, StatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.statStream is not implemented"))
}

func (UnimplementedServiceHandler) GeoStream(context.Context, *connect.BidiStream[Empty, GeoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.geoStream is not implemented"))
}

func (UnimplementedServiceHandler) DomainStream(context.Context, *connect.BidiStream[Empty, DomainResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.domainStream is not implemented"))
}

func (UnimplementedServiceHandler) ConnStream(context.Context, *connect.BidiStream[Empty, ConnResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.connStream is not implemented"))
}

func (UnimplementedServiceHandler) HealthStream(context.Context, *connect.BidiStream[Empty, HealthResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.healthStream is not implemented"))
}

func (UnimplementedServiceHandler) LoginStream(context.Context, *connect.BidiStream[LoginRequest, LoginResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.loginStream is not implemented"))
}

func (UnimplementedServiceHandler) LogoutStream(context.Context, *connect.BidiStream[Empty, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.logoutStream is not implemented"))
}

func (UnimplementedServiceHandler) UserGetStream(context.Context, *connect.BidiStream[Empty, UserResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userGetStream is not implemented"))
}

func (UnimplementedServiceHandler) UserUpdateStream(context.Context, *connect.BidiStream[UserUpdateRequest, UserResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userUpdateStream is not implemented"))
}

func (UnimplementedServiceHandler) UserCreateStream(context.Context, *connect.BidiStream[UserCreateRequest, UserResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userCreateStream is not implemented"))
}

func (UnimplementedServiceHandler) UserDeleteStream(context.Context, *connect.BidiStream[UserDeleteRequest, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.userDeleteStream is not implemented"))
}

func (UnimplementedServiceHandler) ServiceStartStream(context.Context, *connect.BidiStream[DomainServiceRequest, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serviceStartStream is not implemented"))
}

func (UnimplementedServiceHandler) ServiceStopStream(context.Context, *connect.BidiStream[DomainServiceRequest, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serviceStopStream is not implemented"))
}

func (UnimplementedServiceHandler) ServerRestartStream(context.Context, *connect.BidiStream[ServerRequest, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serverRestartStream is not implemented"))
}

func (UnimplementedServiceHandler) ServerStopStream(context.Context, *connect.BidiStream[ServerRequest, ActionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("hamburger.service.serverStopStream is not implemented"))
}
