// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: hamburger.proto

package connect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hamburger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{0}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         string                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_hamburger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{1}
}

func (x *StatRequest) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *StatRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Total         int64                       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Api           int64                       `protobuf:"varint,2,opt,name=api,proto3" json:"api,omitempty"`
	Static        int64                       `protobuf:"varint,3,opt,name=static,proto3" json:"static,omitempty"`
	Fail          int64                       `protobuf:"varint,4,opt,name=fail,proto3" json:"fail,omitempty"`
	Today         int64                       `protobuf:"varint,5,opt,name=today,proto3" json:"today,omitempty"`
	Meta          *StatMeta                   `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	Summary       *StatSummary                `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Series        *StatSeries                 `protobuf:"bytes,8,opt,name=series,proto3" json:"series,omitempty"`
	Connections   map[string]*ConnectionState `protobuf:"bytes,9,rep,name=connections,proto3" json:"connections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Domains       []*DomainSummary            `protobuf:"bytes,10,rep,name=domains,proto3" json:"domains,omitempty"`
	DomainSeries  []*DomainSeriesPoint        `protobuf:"bytes,11,rep,name=domain_series,json=domainSeries,proto3" json:"domain_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_hamburger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{2}
}

func (x *StatResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatResponse) GetApi() int64 {
	if x != nil {
		return x.Api
	}
	return 0
}

func (x *StatResponse) GetStatic() int64 {
	if x != nil {
		return x.Static
	}
	return 0
}

func (x *StatResponse) GetFail() int64 {
	if x != nil {
		return x.Fail
	}
	return 0
}

func (x *StatResponse) GetToday() int64 {
	if x != nil {
		return x.Today
	}
	return 0
}

func (x *StatResponse) GetMeta() *StatMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *StatResponse) GetSummary() *StatSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *StatResponse) GetSeries() *StatSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *StatResponse) GetConnections() map[string]*ConnectionState {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *StatResponse) GetDomains() []*DomainSummary {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *StatResponse) GetDomainSeries() []*DomainSeriesPoint {
	if x != nil {
		return x.DomainSeries
	}
	return nil
}

type StatMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         string                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BucketSeconds int64                  `protobuf:"varint,4,opt,name=bucket_seconds,json=bucketSeconds,proto3" json:"bucket_seconds,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	RetentionDays int32                  `protobuf:"varint,6,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	Capabilities  map[string]bool        `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatMeta) Reset() {
	*x = StatMeta{}
	mi := &file_hamburger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatMeta) ProtoMessage() {}

func (x *StatMeta) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatMeta.ProtoReflect.Descriptor instead.
func (*StatMeta) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{3}
}

func (x *StatMeta) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *StatMeta) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *StatMeta) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *StatMeta) GetBucketSeconds() int64 {
	if x != nil {
		return x.BucketSeconds
	}
	return 0
}

func (x *StatMeta) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *StatMeta) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *StatMeta) GetCapabilities() map[string]bool {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type StatSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests    int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FrontendRequests int64                  `protobuf:"varint,2,opt,name=frontend_requests,json=frontendRequests,proto3" json:"frontend_requests,omitempty"`
	BackendRequests  int64                  `protobuf:"varint,3,opt,name=backend_requests,json=backendRequests,proto3" json:"backend_requests,omitempty"`
	UnknownRequests  int64                  `protobuf:"varint,4,opt,name=unknown_requests,json=unknownRequests,proto3" json:"unknown_requests,omitempty"`
	ErrorRequests    int64                  `protobuf:"varint,5,opt,name=error_requests,json=errorRequests,proto3" json:"error_requests,omitempty"`
	Rps              float64                `protobuf:"fixed64,6,opt,name=rps,proto3" json:"rps,omitempty"`
	ErrorRate        float64                `protobuf:"fixed64,7,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	Status           *StatusSummary         `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Latency          *LatencySummary        `protobuf:"bytes,9,opt,name=latency,proto3" json:"latency,omitempty"`
	Gc               *GCSummary             `protobuf:"bytes,10,opt,name=gc,proto3" json:"gc,omitempty"`
	FrontendTraffic  *TrafficSummary        `protobuf:"bytes,11,opt,name=frontend_traffic,json=frontendTraffic,proto3" json:"frontend_traffic,omitempty"`
	BackendTraffic   *TrafficSummary        `protobuf:"bytes,12,opt,name=backend_traffic,json=backendTraffic,proto3" json:"backend_traffic,omitempty"`
	TotalTraffic     *TrafficSummary        `protobuf:"bytes,13,opt,name=total_traffic,json=totalTraffic,proto3" json:"total_traffic,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatSummary) Reset() {
	*x = StatSummary{}
	mi := &file_hamburger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSummary) ProtoMessage() {}

func (x *StatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSummary.ProtoReflect.Descriptor instead.
func (*StatSummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{4}
}

func (x *StatSummary) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatSummary) GetFrontendRequests() int64 {
	if x != nil {
		return x.FrontendRequests
	}
	return 0
}

func (x *StatSummary) GetBackendRequests() int64 {
	if x != nil {
		return x.BackendRequests
	}
	return 0
}

func (x *StatSummary) GetUnknownRequests() int64 {
	if x != nil {
		return x.UnknownRequests
	}
	return 0
}

func (x *StatSummary) GetErrorRequests() int64 {
	if x != nil {
		return x.ErrorRequests
	}
	return 0
}

func (x *StatSummary) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *StatSummary) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *StatSummary) GetStatus() *StatusSummary {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatSummary) GetLatency() *LatencySummary {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *StatSummary) GetGc() *GCSummary {
	if x != nil {
		return x.Gc
	}
	return nil
}

func (x *StatSummary) GetFrontendTraffic() *TrafficSummary {
	if x != nil {
		return x.FrontendTraffic
	}
	return nil
}

func (x *StatSummary) GetBackendTraffic() *TrafficSummary {
	if x != nil {
		return x.BackendTraffic
	}
	return nil
}

func (x *StatSummary) GetTotalTraffic() *TrafficSummary {
	if x != nil {
		return x.TotalTraffic
	}
	return nil
}

type StatusSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status1Xx     int64                  `protobuf:"varint,1,opt,name=status1xx,json=1xx,proto3" json:"status1xx,omitempty"`
	Status2Xx     int64                  `protobuf:"varint,2,opt,name=status2xx,json=2xx,proto3" json:"status2xx,omitempty"`
	Status3Xx     int64                  `protobuf:"varint,3,opt,name=status3xx,json=3xx,proto3" json:"status3xx,omitempty"`
	Status4Xx     int64                  `protobuf:"varint,4,opt,name=status4xx,json=4xx,proto3" json:"status4xx,omitempty"`
	Status5Xx     int64                  `protobuf:"varint,5,opt,name=status5xx,json=5xx,proto3" json:"status5xx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusSummary) Reset() {
	*x = StatusSummary{}
	mi := &file_hamburger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSummary) ProtoMessage() {}

func (x *StatusSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSummary.ProtoReflect.Descriptor instead.
func (*StatusSummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{5}
}

func (x *StatusSummary) GetStatus1Xx() int64 {
	if x != nil {
		return x.Status1Xx
	}
	return 0
}

func (x *StatusSummary) GetStatus2Xx() int64 {
	if x != nil {
		return x.Status2Xx
	}
	return 0
}

func (x *StatusSummary) GetStatus3Xx() int64 {
	if x != nil {
		return x.Status3Xx
	}
	return 0
}

func (x *StatusSummary) GetStatus4Xx() int64 {
	if x != nil {
		return x.Status4Xx
	}
	return 0
}

func (x *StatusSummary) GetStatus5Xx() int64 {
	if x != nil {
		return x.Status5Xx
	}
	return 0
}

type LatencySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgMs         float64                `protobuf:"fixed64,1,opt,name=avg_ms,json=avgMs,proto3" json:"avg_ms,omitempty"`
	P95Ms         float64                `protobuf:"fixed64,2,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	MaxMs         float64                `protobuf:"fixed64,3,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencySummary) Reset() {
	*x = LatencySummary{}
	mi := &file_hamburger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencySummary) ProtoMessage() {}

func (x *LatencySummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencySummary.ProtoReflect.Descriptor instead.
func (*LatencySummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{6}
}

func (x *LatencySummary) GetAvgMs() float64 {
	if x != nil {
		return x.AvgMs
	}
	return 0
}

func (x *LatencySummary) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *LatencySummary) GetMaxMs() float64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

type TrafficSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestBytes  int64                  `protobuf:"varint,1,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes int64                  `protobuf:"varint,2,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficSummary) Reset() {
	*x = TrafficSummary{}
	mi := &file_hamburger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSummary) ProtoMessage() {}

func (x *TrafficSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSummary.ProtoReflect.Descriptor instead.
func (*TrafficSummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficSummary) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *TrafficSummary) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

func (x *TrafficSummary) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type GCSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cycles          int64                  `protobuf:"varint,1,opt,name=cycles,proto3" json:"cycles,omitempty"`
	ForcedCycles    int64                  `protobuf:"varint,2,opt,name=forced_cycles,json=forcedCycles,proto3" json:"forced_cycles,omitempty"`
	PressurePercent float64                `protobuf:"fixed64,3,opt,name=pressure_percent,json=pressurePercent,proto3" json:"pressure_percent,omitempty"`
	PauseTotalMs    float64                `protobuf:"fixed64,4,opt,name=pause_total_ms,json=pauseTotalMs,proto3" json:"pause_total_ms,omitempty"`
	PauseAvgMs      float64                `protobuf:"fixed64,5,opt,name=pause_avg_ms,json=pauseAvgMs,proto3" json:"pause_avg_ms,omitempty"`
	PauseP95Ms      float64                `protobuf:"fixed64,6,opt,name=pause_p95_ms,json=pauseP95Ms,proto3" json:"pause_p95_ms,omitempty"`
	PauseMaxMs      float64                `protobuf:"fixed64,7,opt,name=pause_max_ms,json=pauseMaxMs,proto3" json:"pause_max_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCSummary) Reset() {
	*x = GCSummary{}
	mi := &file_hamburger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSummary) ProtoMessage() {}

func (x *GCSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSummary.ProtoReflect.Descriptor instead.
func (*GCSummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{8}
}

func (x *GCSummary) GetCycles() int64 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *GCSummary) GetForcedCycles() int64 {
	if x != nil {
		return x.ForcedCycles
	}
	return 0
}

func (x *GCSummary) GetPressurePercent() float64 {
	if x != nil {
		return x.PressurePercent
	}
	return 0
}

func (x *GCSummary) GetPauseTotalMs() float64 {
	if x != nil {
		return x.PauseTotalMs
	}
	return 0
}

func (x *GCSummary) GetPauseAvgMs() float64 {
	if x != nil {
		return x.PauseAvgMs
	}
	return 0
}

func (x *GCSummary) GetPauseP95Ms() float64 {
	if x != nil {
		return x.PauseP95Ms
	}
	return 0
}

func (x *GCSummary) GetPauseMaxMs() float64 {
	if x != nil {
		return x.PauseMaxMs
	}
	return 0
}

type StatSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RequestSeriesPoint  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Traffic       []*TrafficSeriesPoint  `protobuf:"bytes,2,rep,name=traffic,proto3" json:"traffic,omitempty"`
	Gc            []*GCSeriesPoint       `protobuf:"bytes,3,rep,name=gc,proto3" json:"gc,omitempty"`
	System        []*SystemSeriesPoint   `protobuf:"bytes,4,rep,name=system,proto3" json:"system,omitempty"`
	Process       []*ProcessSeriesPoint  `protobuf:"bytes,5,rep,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSeries) Reset() {
	*x = StatSeries{}
	mi := &file_hamburger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSeries) ProtoMessage() {}

func (x *StatSeries) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSeries.ProtoReflect.Descriptor instead.
func (*StatSeries) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{9}
}

func (x *StatSeries) GetRequests() []*RequestSeriesPoint {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *StatSeries) GetTraffic() []*TrafficSeriesPoint {
	if x != nil {
		return x.Traffic
	}
	return nil
}

func (x *StatSeries) GetGc() []*GCSeriesPoint {
	if x != nil {
		return x.Gc
	}
	return nil
}

func (x *StatSeries) GetSystem() []*SystemSeriesPoint {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *StatSeries) GetProcess() []*ProcessSeriesPoint {
	if x != nil {
		return x.Process
	}
	return nil
}

type RequestSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Frontend      int64                  `protobuf:"varint,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	Backend       int64                  `protobuf:"varint,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Unknown       int64                  `protobuf:"varint,4,opt,name=unknown,proto3" json:"unknown,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Errors        int64                  `protobuf:"varint,6,opt,name=errors,proto3" json:"errors,omitempty"`
	Status1Xx     int64                  `protobuf:"varint,7,opt,name=status1xx,json=status_1xx,proto3" json:"status1xx,omitempty"`
	Status2Xx     int64                  `protobuf:"varint,8,opt,name=status2xx,json=status_2xx,proto3" json:"status2xx,omitempty"`
	Status3Xx     int64                  `protobuf:"varint,9,opt,name=status3xx,json=status_3xx,proto3" json:"status3xx,omitempty"`
	Status4Xx     int64                  `protobuf:"varint,10,opt,name=status4xx,json=status_4xx,proto3" json:"status4xx,omitempty"`
	Status5Xx     int64                  `protobuf:"varint,11,opt,name=status5xx,json=status_5xx,proto3" json:"status5xx,omitempty"`
	Rps           float64                `protobuf:"fixed64,12,opt,name=rps,proto3" json:"rps,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,13,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,14,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	MaxLatencyMs  float64                `protobuf:"fixed64,15,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSeriesPoint) Reset() {
	*x = RequestSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSeriesPoint) ProtoMessage() {}

func (x *RequestSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSeriesPoint.ProtoReflect.Descriptor instead.
func (*RequestSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{10}
}

func (x *RequestSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RequestSeriesPoint) GetFrontend() int64 {
	if x != nil {
		return x.Frontend
	}
	return 0
}

func (x *RequestSeriesPoint) GetBackend() int64 {
	if x != nil {
		return x.Backend
	}
	return 0
}

func (x *RequestSeriesPoint) GetUnknown() int64 {
	if x != nil {
		return x.Unknown
	}
	return 0
}

func (x *RequestSeriesPoint) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RequestSeriesPoint) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *RequestSeriesPoint) GetStatus1Xx() int64 {
	if x != nil {
		return x.Status1Xx
	}
	return 0
}

func (x *RequestSeriesPoint) GetStatus2Xx() int64 {
	if x != nil {
		return x.Status2Xx
	}
	return 0
}

func (x *RequestSeriesPoint) GetStatus3Xx() int64 {
	if x != nil {
		return x.Status3Xx
	}
	return 0
}

func (x *RequestSeriesPoint) GetStatus4Xx() int64 {
	if x != nil {
		return x.Status4Xx
	}
	return 0
}

func (x *RequestSeriesPoint) GetStatus5Xx() int64 {
	if x != nil {
		return x.Status5Xx
	}
	return 0
}

func (x *RequestSeriesPoint) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *RequestSeriesPoint) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *RequestSeriesPoint) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *RequestSeriesPoint) GetMaxLatencyMs() float64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

type TrafficSeriesPoint struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FrontendRequestBytes  int64                  `protobuf:"varint,2,opt,name=frontend_request_bytes,json=frontendRequestBytes,proto3" json:"frontend_request_bytes,omitempty"`
	FrontendResponseBytes int64                  `protobuf:"varint,3,opt,name=frontend_response_bytes,json=frontendResponseBytes,proto3" json:"frontend_response_bytes,omitempty"`
	BackendRequestBytes   int64                  `protobuf:"varint,4,opt,name=backend_request_bytes,json=backendRequestBytes,proto3" json:"backend_request_bytes,omitempty"`
	BackendResponseBytes  int64                  `protobuf:"varint,5,opt,name=backend_response_bytes,json=backendResponseBytes,proto3" json:"backend_response_bytes,omitempty"`
	RequestBytes          int64                  `protobuf:"varint,6,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes         int64                  `protobuf:"varint,7,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrafficSeriesPoint) Reset() {
	*x = TrafficSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSeriesPoint) ProtoMessage() {}

func (x *TrafficSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSeriesPoint.ProtoReflect.Descriptor instead.
func (*TrafficSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{11}
}

func (x *TrafficSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TrafficSeriesPoint) GetFrontendRequestBytes() int64 {
	if x != nil {
		return x.FrontendRequestBytes
	}
	return 0
}

func (x *TrafficSeriesPoint) GetFrontendResponseBytes() int64 {
	if x != nil {
		return x.FrontendResponseBytes
	}
	return 0
}

func (x *TrafficSeriesPoint) GetBackendRequestBytes() int64 {
	if x != nil {
		return x.BackendRequestBytes
	}
	return 0
}

func (x *TrafficSeriesPoint) GetBackendResponseBytes() int64 {
	if x != nil {
		return x.BackendResponseBytes
	}
	return 0
}

func (x *TrafficSeriesPoint) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *TrafficSeriesPoint) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

type GCSeriesPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cycles          int64                  `protobuf:"varint,2,opt,name=cycles,proto3" json:"cycles,omitempty"`
	ForcedCycles    int64                  `protobuf:"varint,3,opt,name=forced_cycles,json=forcedCycles,proto3" json:"forced_cycles,omitempty"`
	PressurePercent float64                `protobuf:"fixed64,4,opt,name=pressure_percent,json=pressurePercent,proto3" json:"pressure_percent,omitempty"`
	PauseTotalMs    float64                `protobuf:"fixed64,5,opt,name=pause_total_ms,json=pauseTotalMs,proto3" json:"pause_total_ms,omitempty"`
	PauseAvgMs      float64                `protobuf:"fixed64,6,opt,name=pause_avg_ms,json=pauseAvgMs,proto3" json:"pause_avg_ms,omitempty"`
	PauseP95Ms      float64                `protobuf:"fixed64,7,opt,name=pause_p95_ms,json=pauseP95Ms,proto3" json:"pause_p95_ms,omitempty"`
	PauseMaxMs      float64                `protobuf:"fixed64,8,opt,name=pause_max_ms,json=pauseMaxMs,proto3" json:"pause_max_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCSeriesPoint) Reset() {
	*x = GCSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCSeriesPoint) ProtoMessage() {}

func (x *GCSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCSeriesPoint.ProtoReflect.Descriptor instead.
func (*GCSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{12}
}

func (x *GCSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GCSeriesPoint) GetCycles() int64 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *GCSeriesPoint) GetForcedCycles() int64 {
	if x != nil {
		return x.ForcedCycles
	}
	return 0
}

func (x *GCSeriesPoint) GetPressurePercent() float64 {
	if x != nil {
		return x.PressurePercent
	}
	return 0
}

func (x *GCSeriesPoint) GetPauseTotalMs() float64 {
	if x != nil {
		return x.PauseTotalMs
	}
	return 0
}

func (x *GCSeriesPoint) GetPauseAvgMs() float64 {
	if x != nil {
		return x.PauseAvgMs
	}
	return 0
}

func (x *GCSeriesPoint) GetPauseP95Ms() float64 {
	if x != nil {
		return x.PauseP95Ms
	}
	return 0
}

func (x *GCSeriesPoint) GetPauseMaxMs() float64 {
	if x != nil {
		return x.PauseMaxMs
	}
	return 0
}

type SystemSeriesPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent        *float64               `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3,oneof" json:"cpu_percent,omitempty"`
	CpuPeakPercent    *float64               `protobuf:"fixed64,3,opt,name=cpu_peak_percent,json=cpuPeakPercent,proto3,oneof" json:"cpu_peak_percent,omitempty"`
	MemoryPercent     *float64               `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3,oneof" json:"memory_percent,omitempty"`
	MemoryPeakPercent *float64               `protobuf:"fixed64,5,opt,name=memory_peak_percent,json=memoryPeakPercent,proto3,oneof" json:"memory_peak_percent,omitempty"`
	NetworkRxBytes    *int64                 `protobuf:"varint,6,opt,name=network_rx_bytes,json=networkRxBytes,proto3,oneof" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes    *int64                 `protobuf:"varint,7,opt,name=network_tx_bytes,json=networkTxBytes,proto3,oneof" json:"network_tx_bytes,omitempty"`
	DiskReadBytes     *int64                 `protobuf:"varint,8,opt,name=disk_read_bytes,json=diskReadBytes,proto3,oneof" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes    *int64                 `protobuf:"varint,9,opt,name=disk_write_bytes,json=diskWriteBytes,proto3,oneof" json:"disk_write_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemSeriesPoint) Reset() {
	*x = SystemSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSeriesPoint) ProtoMessage() {}

func (x *SystemSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSeriesPoint.ProtoReflect.Descriptor instead.
func (*SystemSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{13}
}

func (x *SystemSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SystemSeriesPoint) GetCpuPercent() float64 {
	if x != nil && x.CpuPercent != nil {
		return *x.CpuPercent
	}
	return 0
}

func (x *SystemSeriesPoint) GetCpuPeakPercent() float64 {
	if x != nil && x.CpuPeakPercent != nil {
		return *x.CpuPeakPercent
	}
	return 0
}

func (x *SystemSeriesPoint) GetMemoryPercent() float64 {
	if x != nil && x.MemoryPercent != nil {
		return *x.MemoryPercent
	}
	return 0
}

func (x *SystemSeriesPoint) GetMemoryPeakPercent() float64 {
	if x != nil && x.MemoryPeakPercent != nil {
		return *x.MemoryPeakPercent
	}
	return 0
}

func (x *SystemSeriesPoint) GetNetworkRxBytes() int64 {
	if x != nil && x.NetworkRxBytes != nil {
		return *x.NetworkRxBytes
	}
	return 0
}

func (x *SystemSeriesPoint) GetNetworkTxBytes() int64 {
	if x != nil && x.NetworkTxBytes != nil {
		return *x.NetworkTxBytes
	}
	return 0
}

func (x *SystemSeriesPoint) GetDiskReadBytes() int64 {
	if x != nil && x.DiskReadBytes != nil {
		return *x.DiskReadBytes
	}
	return 0
}

func (x *SystemSeriesPoint) GetDiskWriteBytes() int64 {
	if x != nil && x.DiskWriteBytes != nil {
		return *x.DiskWriteBytes
	}
	return 0
}

type ProcessSeriesPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent        *float64               `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3,oneof" json:"cpu_percent,omitempty"`
	CpuPeakPercent    *float64               `protobuf:"fixed64,3,opt,name=cpu_peak_percent,json=cpuPeakPercent,proto3,oneof" json:"cpu_peak_percent,omitempty"`
	MemoryBytes       *int64                 `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3,oneof" json:"memory_bytes,omitempty"`
	MemoryPeakBytes   *int64                 `protobuf:"varint,5,opt,name=memory_peak_bytes,json=memoryPeakBytes,proto3,oneof" json:"memory_peak_bytes,omitempty"`
	MemoryPercent     *float64               `protobuf:"fixed64,6,opt,name=memory_percent,json=memoryPercent,proto3,oneof" json:"memory_percent,omitempty"`
	MemoryPeakPercent *float64               `protobuf:"fixed64,7,opt,name=memory_peak_percent,json=memoryPeakPercent,proto3,oneof" json:"memory_peak_percent,omitempty"`
	DiskReadBytes     *int64                 `protobuf:"varint,8,opt,name=disk_read_bytes,json=diskReadBytes,proto3,oneof" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes    *int64                 `protobuf:"varint,9,opt,name=disk_write_bytes,json=diskWriteBytes,proto3,oneof" json:"disk_write_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessSeriesPoint) Reset() {
	*x = ProcessSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSeriesPoint) ProtoMessage() {}

func (x *ProcessSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSeriesPoint.ProtoReflect.Descriptor instead.
func (*ProcessSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ProcessSeriesPoint) GetCpuPercent() float64 {
	if x != nil && x.CpuPercent != nil {
		return *x.CpuPercent
	}
	return 0
}

func (x *ProcessSeriesPoint) GetCpuPeakPercent() float64 {
	if x != nil && x.CpuPeakPercent != nil {
		return *x.CpuPeakPercent
	}
	return 0
}

func (x *ProcessSeriesPoint) GetMemoryBytes() int64 {
	if x != nil && x.MemoryBytes != nil {
		return *x.MemoryBytes
	}
	return 0
}

func (x *ProcessSeriesPoint) GetMemoryPeakBytes() int64 {
	if x != nil && x.MemoryPeakBytes != nil {
		return *x.MemoryPeakBytes
	}
	return 0
}

func (x *ProcessSeriesPoint) GetMemoryPercent() float64 {
	if x != nil && x.MemoryPercent != nil {
		return *x.MemoryPercent
	}
	return 0
}

func (x *ProcessSeriesPoint) GetMemoryPeakPercent() float64 {
	if x != nil && x.MemoryPeakPercent != nil {
		return *x.MemoryPeakPercent
	}
	return 0
}

func (x *ProcessSeriesPoint) GetDiskReadBytes() int64 {
	if x != nil && x.DiskReadBytes != nil {
		return *x.DiskReadBytes
	}
	return 0
}

func (x *ProcessSeriesPoint) GetDiskWriteBytes() int64 {
	if x != nil && x.DiskWriteBytes != nil {
		return *x.DiskWriteBytes
	}
	return 0
}

type DomainSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Requests      int64                  `protobuf:"varint,2,opt,name=requests,proto3" json:"requests,omitempty"`
	Errors        int64                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	RequestBytes  int64                  `protobuf:"varint,4,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes int64                  `protobuf:"varint,5,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSummary) Reset() {
	*x = DomainSummary{}
	mi := &file_hamburger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSummary) ProtoMessage() {}

func (x *DomainSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSummary.ProtoReflect.Descriptor instead.
func (*DomainSummary) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{15}
}

func (x *DomainSummary) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainSummary) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *DomainSummary) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *DomainSummary) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *DomainSummary) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

type DomainSeriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Requests      int64                  `protobuf:"varint,2,opt,name=requests,proto3" json:"requests,omitempty"`
	Errors        int64                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	RequestBytes  int64                  `protobuf:"varint,4,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	ResponseBytes int64                  `protobuf:"varint,5,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSeriesPoint) Reset() {
	*x = DomainSeriesPoint{}
	mi := &file_hamburger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSeriesPoint) ProtoMessage() {}

func (x *DomainSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSeriesPoint.ProtoReflect.Descriptor instead.
func (*DomainSeriesPoint) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{16}
}

func (x *DomainSeriesPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *DomainSeriesPoint) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *DomainSeriesPoint) GetErrors() int64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *DomainSeriesPoint) GetRequestBytes() int64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *DomainSeriesPoint) GetResponseBytes() int64 {
	if x != nil {
		return x.ResponseBytes
	}
	return 0
}

type ConnectionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	New           int64                  `protobuf:"varint,1,opt,name=new,proto3" json:"new,omitempty"`
	Active        int64                  `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Idle          int64                  `protobuf:"varint,3,opt,name=idle,proto3" json:"idle,omitempty"`
	Hijacked      int64                  `protobuf:"varint,4,opt,name=hijacked,proto3" json:"hijacked,omitempty"`
	Closed        int64                  `protobuf:"varint,5,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionState) Reset() {
	*x = ConnectionState{}
	mi := &file_hamburger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionState) ProtoMessage() {}

func (x *ConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionState.ProtoReflect.Descriptor instead.
func (*ConnectionState) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectionState) GetNew() int64 {
	if x != nil {
		return x.New
	}
	return 0
}

func (x *ConnectionState) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *ConnectionState) GetIdle() int64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *ConnectionState) GetHijacked() int64 {
	if x != nil {
		return x.Hijacked
	}
	return 0
}

func (x *ConnectionState) GetClosed() int64 {
	if x != nil {
		return x.Closed
	}
	return 0
}

type GeoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]int64       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoResponse) Reset() {
	*x = GeoResponse{}
	mi := &file_hamburger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoResponse) ProtoMessage() {}

func (x *GeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoResponse.ProtoReflect.Descriptor instead.
func (*GeoResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{18}
}

func (x *GeoResponse) GetValues() map[string]int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type DomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]int64       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainResponse) Reset() {
	*x = DomainResponse{}
	mi := &file_hamburger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainResponse) ProtoMessage() {}

func (x *DomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainResponse.ProtoReflect.Descriptor instead.
func (*DomainResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{19}
}

func (x *DomainResponse) GetValues() map[string]int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConnResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Values        map[string]*ConnectionState `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnResponse) Reset() {
	*x = ConnResponse{}
	mi := &file_hamburger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnResponse) ProtoMessage() {}

func (x *ConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnResponse.ProtoReflect.Descriptor instead.
func (*ConnResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{20}
}

func (x *ConnResponse) GetValues() map[string]*ConnectionState {
	if x != nil {
		return x.Values
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_hamburger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_hamburger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{22}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_hamburger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{23}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_hamburger_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{24}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_hamburger_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{25}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_hamburger_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{26}
}

func (x *UserUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserUpdateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserUpdateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_hamburger_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{27}
}

func (x *UserCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserCreateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_hamburger_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{28}
}

func (x *UserDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DomainServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainServiceRequest) Reset() {
	*x = DomainServiceRequest{}
	mi := &file_hamburger_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainServiceRequest) ProtoMessage() {}

func (x *DomainServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainServiceRequest.ProtoReflect.Descriptor instead.
func (*DomainServiceRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{29}
}

func (x *DomainServiceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	mi := &file_hamburger_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{30}
}

func (x *ServerRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_hamburger_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hamburger_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_hamburger_proto_rawDescGZIP(), []int{31}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hamburger_proto protoreflect.FileDescriptor

const file_hamburger_proto_rawDesc = "" +
	"\n" +
	"\x0fhamburger.proto\x12\thamburger\"\a\n" +
	"\x05Empty\";\n" +
	"\vStatRequest\x12\x14\n" +
	"\x05range\x18\x01 \x01(\tR\x05range\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\xa1\x04\n" +
	"\fStatResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x10\n" +
	"\x03api\x18\x02 \x01(\x03R\x03api\x12\x16\n" +
	"\x06static\x18\x03 \x01(\x03R\x06static\x12\x12\n" +
	"\x04fail\x18\x04 \x01(\x03R\x04fail\x12\x14\n" +
	"\x05today\x18\x05 \x01(\x03R\x05today\x12'\n" +
	"\x04meta\x18\x06 \x01(\v2\x13.hamburger.StatMetaR\x04meta\x120\n" +
	"\asummary\x18\a \x01(\v2\x16.hamburger.StatSummaryR\asummary\x12-\n" +
	"\x06series\x18\b \x01(\v2\x15.hamburger.StatSeriesR\x06series\x12J\n" +
	"\vconnections\x18\t \x03(\v2(.hamburger.StatResponse.ConnectionsEntryR\vconnections\x122\n" +
	"\adomains\x18\n" +
	" \x03(\v2\x18.hamburger.DomainSummaryR\adomains\x12A\n" +
	"\rdomain_series\x18\v \x03(\v2\x1c.hamburger.DomainSeriesPointR\fdomainSeries\x1aZ\n" +
	"\x10ConnectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.hamburger.ConnectionStateR\x05value:\x028\x01\"\xd7\x02\n" +
	"\bStatMeta\x12\x14\n" +
	"\x05range\x18\x01 \x01(\tR\x05range\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12%\n" +
	"\x0ebucket_seconds\x18\x04 \x01(\x03R\rbucketSeconds\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\tR\vgeneratedAt\x12%\n" +
	"\x0eretention_days\x18\x06 \x01(\x05R\rretentionDays\x12I\n" +
	"\fcapabilities\x18\a \x03(\v2%.hamburger.StatMeta.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xe6\x04\n" +
	"\vStatSummary\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12+\n" +
	"\x11frontend_requests\x18\x02 \x01(\x03R\x10frontendRequests\x12)\n" +
	"\x10backend_requests\x18\x03 \x01(\x03R\x0fbackendRequests\x12)\n" +
	"\x10unknown_requests\x18\x04 \x01(\x03R\x0funknownRequests\x12%\n" +
	"\x0eerror_requests\x18\x05 \x01(\x03R\rerrorRequests\x12\x10\n" +
	"\x03rps\x18\x06 \x01(\x01R\x03rps\x12\x1d\n" +
	"\n" +
	"error_rate\x18\a \x01(\x01R\terrorRate\x120\n" +
	"\x06status\x18\b \x01(\v2\x18.hamburger.StatusSummaryR\x06status\x123\n" +
	"\alatency\x18\t \x01(\v2\x19.hamburger.LatencySummaryR\alatency\x12$\n" +
	"\x02gc\x18\n" +
	" \x01(\v2\x14.hamburger.GCSummaryR\x02gc\x12D\n" +
	"\x10frontend_traffic\x18\v \x01(\v2\x19.hamburger.TrafficSummaryR\x0ffrontendTraffic\x12B\n" +
	"\x0fbackend_traffic\x18\f \x01(\v2\x19.hamburger.TrafficSummaryR\x0ebackendTraffic\x12>\n" +
	"\rtotal_traffic\x18\r \x01(\v2\x19.hamburger.TrafficSummaryR\ftotalTraffic\"\x87\x01\n" +
	"\rStatusSummary\x12\x16\n" +
	"\tstatus1xx\x18\x01 \x01(\x03R\x031xx\x12\x16\n" +
	"\tstatus2xx\x18\x02 \x01(\x03R\x032xx\x12\x16\n" +
	"\tstatus3xx\x18\x03 \x01(\x03R\x033xx\x12\x16\n" +
	"\tstatus4xx\x18\x04 \x01(\x03R\x034xx\x12\x16\n" +
	"\tstatus5xx\x18\x05 \x01(\x03R\x035xx\"U\n" +
	"\x0eLatencySummary\x12\x15\n" +
	"\x06avg_ms\x18\x01 \x01(\x01R\x05avgMs\x12\x15\n" +
	"\x06p95_ms\x18\x02 \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06max_ms\x18\x03 \x01(\x01R\x05maxMs\"}\n" +
	"\x0eTrafficSummary\x12#\n" +
	"\rrequest_bytes\x18\x01 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\x02 \x01(\x03R\rresponseBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\"\xff\x01\n" +
	"\tGCSummary\x12\x16\n" +
	"\x06cycles\x18\x01 \x01(\x03R\x06cycles\x12#\n" +
	"\rforced_cycles\x18\x02 \x01(\x03R\fforcedCycles\x12)\n" +
	"\x10pressure_percent\x18\x03 \x01(\x01R\x0fpressurePercent\x12$\n" +
	"\x0epause_total_ms\x18\x04 \x01(\x01R\fpauseTotalMs\x12 \n" +
	"\fpause_avg_ms\x18\x05 \x01(\x01R\n" +
	"pauseAvgMs\x12 \n" +
	"\fpause_p95_ms\x18\x06 \x01(\x01R\n" +
	"pauseP95Ms\x12 \n" +
	"\fpause_max_ms\x18\a \x01(\x01R\n" +
	"pauseMaxMs\"\x99\x02\n" +
	"\n" +
	"StatSeries\x129\n" +
	"\brequests\x18\x01 \x03(\v2\x1d.hamburger.RequestSeriesPointR\brequests\x127\n" +
	"\atraffic\x18\x02 \x03(\v2\x1d.hamburger.TrafficSeriesPointR\atraffic\x12(\n" +
	"\x02gc\x18\x03 \x03(\v2\x18.hamburger.GCSeriesPointR\x02gc\x124\n" +
	"\x06system\x18\x04 \x03(\v2\x1c.hamburger.SystemSeriesPointR\x06system\x127\n" +
	"\aprocess\x18\x05 \x03(\v2\x1d.hamburger.ProcessSeriesPointR\aprocess\"\xcf\x03\n" +
	"\x12RequestSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\bfrontend\x18\x02 \x01(\x03R\bfrontend\x12\x18\n" +
	"\abackend\x18\x03 \x01(\x03R\abackend\x12\x18\n" +
	"\aunknown\x18\x04 \x01(\x03R\aunknown\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12\x16\n" +
	"\x06errors\x18\x06 \x01(\x03R\x06errors\x12\x1d\n" +
	"\tstatus1xx\x18\a \x01(\x03R\n" +
	"status_1xx\x12\x1d\n" +
	"\tstatus2xx\x18\b \x01(\x03R\n" +
	"status_2xx\x12\x1d\n" +
	"\tstatus3xx\x18\t \x01(\x03R\n" +
	"status_3xx\x12\x1d\n" +
	"\tstatus4xx\x18\n" +
	" \x01(\x03R\n" +
	"status_4xx\x12\x1d\n" +
	"\tstatus5xx\x18\v \x01(\x03R\n" +
	"status_5xx\x12\x10\n" +
	"\x03rps\x18\f \x01(\x01R\x03rps\x12$\n" +
	"\x0eavg_latency_ms\x18\r \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x0e \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0emax_latency_ms\x18\x0f \x01(\x01R\fmaxLatencyMs\"\xd6\x02\n" +
	"\x12TrafficSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x124\n" +
	"\x16frontend_request_bytes\x18\x02 \x01(\x03R\x14frontendRequestBytes\x126\n" +
	"\x17frontend_response_bytes\x18\x03 \x01(\x03R\x15frontendResponseBytes\x122\n" +
	"\x15backend_request_bytes\x18\x04 \x01(\x03R\x13backendRequestBytes\x124\n" +
	"\x16backend_response_bytes\x18\x05 \x01(\x03R\x14backendResponseBytes\x12#\n" +
	"\rrequest_bytes\x18\x06 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\a \x01(\x03R\rresponseBytes\"\xa1\x02\n" +
	"\rGCSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06cycles\x18\x02 \x01(\x03R\x06cycles\x12#\n" +
	"\rforced_cycles\x18\x03 \x01(\x03R\fforcedCycles\x12)\n" +
	"\x10pressure_percent\x18\x04 \x01(\x01R\x0fpressurePercent\x12$\n" +
	"\x0epause_total_ms\x18\x05 \x01(\x01R\fpauseTotalMs\x12 \n" +
	"\fpause_avg_ms\x18\x06 \x01(\x01R\n" +
	"pauseAvgMs\x12 \n" +
	"\fpause_p95_ms\x18\a \x01(\x01R\n" +
	"pauseP95Ms\x12 \n" +
	"\fpause_max_ms\x18\b \x01(\x01R\n" +
	"pauseMaxMs\"\xc4\x04\n" +
	"\x11SystemSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12$\n" +
	"\vcpu_percent\x18\x02 \x01(\x01H\x00R\n" +
	"cpuPercent\x88\x01\x01\x12-\n" +
	"\x10cpu_peak_percent\x18\x03 \x01(\x01H\x01R\x0ecpuPeakPercent\x88\x01\x01\x12*\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01H\x02R\rmemoryPercent\x88\x01\x01\x123\n" +
	"\x13memory_peak_percent\x18\x05 \x01(\x01H\x03R\x11memoryPeakPercent\x88\x01\x01\x12-\n" +
	"\x10network_rx_bytes\x18\x06 \x01(\x03H\x04R\x0enetworkRxBytes\x88\x01\x01\x12-\n" +
	"\x10network_tx_bytes\x18\a \x01(\x03H\x05R\x0enetworkTxBytes\x88\x01\x01\x12+\n" +
	"\x0fdisk_read_bytes\x18\b \x01(\x03H\x06R\rdiskReadBytes\x88\x01\x01\x12-\n" +
	"\x10disk_write_bytes\x18\t \x01(\x03H\aR\x0ediskWriteBytes\x88\x01\x01B\x0e\n" +
	"\f_cpu_percentB\x13\n" +
	"\x11_cpu_peak_percentB\x11\n" +
	"\x0f_memory_percentB\x16\n" +
	"\x14_memory_peak_percentB\x13\n" +
	"\x11_network_rx_bytesB\x13\n" +
	"\x11_network_tx_bytesB\x12\n" +
	"\x10_disk_read_bytesB\x13\n" +
	"\x11_disk_write_bytes\"\xbd\x04\n" +
	"\x12ProcessSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12$\n" +
	"\vcpu_percent\x18\x02 \x01(\x01H\x00R\n" +
	"cpuPercent\x88\x01\x01\x12-\n" +
	"\x10cpu_peak_percent\x18\x03 \x01(\x01H\x01R\x0ecpuPeakPercent\x88\x01\x01\x12&\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03H\x02R\vmemoryBytes\x88\x01\x01\x12/\n" +
	"\x11memory_peak_bytes\x18\x05 \x01(\x03H\x03R\x0fmemoryPeakBytes\x88\x01\x01\x12*\n" +
	"\x0ememory_percent\x18\x06 \x01(\x01H\x04R\rmemoryPercent\x88\x01\x01\x123\n" +
	"\x13memory_peak_percent\x18\a \x01(\x01H\x05R\x11memoryPeakPercent\x88\x01\x01\x12+\n" +
	"\x0fdisk_read_bytes\x18\b \x01(\x03H\x06R\rdiskReadBytes\x88\x01\x01\x12-\n" +
	"\x10disk_write_bytes\x18\t \x01(\x03H\aR\x0ediskWriteBytes\x88\x01\x01B\x0e\n" +
	"\f_cpu_percentB\x13\n" +
	"\x11_cpu_peak_percentB\x0f\n" +
	"\r_memory_bytesB\x14\n" +
	"\x12_memory_peak_bytesB\x11\n" +
	"\x0f_memory_percentB\x16\n" +
	"\x14_memory_peak_percentB\x12\n" +
	"\x10_disk_read_bytesB\x13\n" +
	"\x11_disk_write_bytes\"\xa7\x01\n" +
	"\rDomainSummary\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1a\n" +
	"\brequests\x18\x02 \x01(\x03R\brequests\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x03R\x06errors\x12#\n" +
	"\rrequest_bytes\x18\x04 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\x05 \x01(\x03R\rresponseBytes\"\xb1\x01\n" +
	"\x11DomainSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1a\n" +
	"\brequests\x18\x02 \x01(\x03R\brequests\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x03R\x06errors\x12#\n" +
	"\rrequest_bytes\x18\x04 \x01(\x03R\frequestBytes\x12%\n" +
	"\x0eresponse_bytes\x18\x05 \x01(\x03R\rresponseBytes\"\x83\x01\n" +
	"\x0fConnectionState\x12\x10\n" +
	"\x03new\x18\x01 \x01(\x03R\x03new\x12\x16\n" +
	"\x06active\x18\x02 \x01(\x03R\x06active\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x03R\x04idle\x12\x1a\n" +
	"\bhijacked\x18\x04 \x01(\x03R\bhijacked\x12\x16\n" +
	"\x06closed\x18\x05 \x01(\x03R\x06closed\"\x84\x01\n" +
	"\vGeoResponse\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".hamburger.GeoResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8a\x01\n" +
	"\x0eDomainResponse\x12=\n" +
	"\x06values\x18\x01 \x03(\v2%.hamburger.DomainResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa2\x01\n" +
	"\fConnResponse\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.hamburger.ConnResponse.ValuesEntryR\x06values\x1aU\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.hamburger.ConnectionStateR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x0eHealthResponse\x12=\n" +
	"\x06values\x18\x01 \x03(\v2%.hamburger.HealthResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.hamburger.UserR\x04user\"3\n" +
	"\fUserResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.hamburger.UserR\x04user\"V\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\x7f\n" +
	"\x11UserUpdateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x7f\n" +
	"\x11UserCreateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"/\n" +
	"\x11UserDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\".\n" +
	"\x14DomainServiceRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"'\n" +
	"\rServerRequest\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe9\x0f\n" +
	"\aservice\x127\n" +
	"\x04stat\x12\x16.hamburger.StatRequest\x1a\x17.hamburger.StatResponse\x12/\n" +
	"\x03geo\x12\x10.hamburger.Empty\x1a\x16.hamburger.GeoResponse\x125\n" +
	"\x06domain\x12\x10.hamburger.Empty\x1a\x19.hamburger.DomainResponse\x121\n" +
	"\x04conn\x12\x10.hamburger.Empty\x1a\x17.hamburger.ConnResponse\x125\n" +
	"\x06health\x12\x10.hamburger.Empty\x1a\x19.hamburger.HealthResponse\x12:\n" +
	"\x05login\x12\x17.hamburger.LoginRequest\x1a\x18.hamburger.LoginResponse\x125\n" +
	"\x06logout\x12\x10.hamburger.Empty\x1a\x19.hamburger.ActionResponse\x124\n" +
	"\auserGet\x12\x10.hamburger.Empty\x1a\x17.hamburger.UserResponse\x12C\n" +
	"\n" +
	"userUpdate\x12\x1c.hamburger.UserUpdateRequest\x1a\x17.hamburger.UserResponse\x12C\n" +
	"\n" +
	"userCreate\x12\x1c.hamburger.UserCreateRequest\x1a\x17.hamburger.UserResponse\x12E\n" +
	"\n" +
	"userDelete\x12\x1c.hamburger.UserDeleteRequest\x1a\x19.hamburger.ActionResponse\x12J\n" +
	"\fserviceStart\x12\x1f.hamburger.DomainServiceRequest\x1a\x19.hamburger.ActionResponse\x12I\n" +
	"\vserviceStop\x12\x1f.hamburger.DomainServiceRequest\x1a\x19.hamburger.ActionResponse\x12D\n" +
	"\rserverRestart\x12\x18.hamburger.ServerRequest\x1a\x19.hamburger.ActionResponse\x12A\n" +
	"\n" +
	"serverStop\x12\x18.hamburger.ServerRequest\x1a\x19.hamburger.ActionResponse\x12A\n" +
	"\n" +
	"statStream\x12\x16.hamburger.StatRequest\x1a\x17.hamburger.StatResponse(\x010\x01\x129\n" +
	"\tgeoStream\x12\x10.hamburger.Empty\x1a\x16.hamburger.GeoResponse(\x010\x01\x12?\n" +
	"\fdomainStream\x12\x10.hamburger.Empty\x1a\x19.hamburger.DomainResponse(\x010\x01\x12;\n" +
	"\n" +
	"connStream\x12\x10.hamburger.Empty\x1a\x17.hamburger.ConnResponse(\x010\x01\x12?\n" +
	"\fhealthStream\x12\x10.hamburger.Empty\x1a\x19.hamburger.HealthResponse(\x010\x01\x12D\n" +
	"\vloginStream\x12\x17.hamburger.LoginRequest\x1a\x18.hamburger.LoginResponse(\x010\x01\x12?\n" +
	"\flogoutStream\x12\x10.hamburger.Empty\x1a\x19.hamburger.ActionResponse(\x010\x01\x12>\n" +
	"\ruserGetStream\x12\x10.hamburger.Empty\x1a\x17.hamburger.UserResponse(\x010\x01\x12M\n" +
	"\x10userUpdateStream\x12\x1c.hamburger.UserUpdateRequest\x1a\x17.hamburger.UserResponse(\x010\x01\x12M\n" +
	"\x10userCreateStream\x12\x1c.hamburger.UserCreateRequest\x1a\x17.hamburger.UserResponse(\x010\x01\x12O\n" +
	"\x10userDeleteStream\x12\x1c.hamburger.UserDeleteRequest\x1a\x19.hamburger.ActionResponse(\x010\x01\x12T\n" +
	"\x12serviceStartStream\x12\x1f.hamburger.DomainServiceRequest\x1a\x19.hamburger.ActionResponse(\x010\x01\x12S\n" +
	"\x11serviceStopStream\x12\x1f.hamburger.DomainServiceRequest\x1a\x19.hamburger.ActionResponse(\x010\x01\x12N\n" +
	"\x13serverRestartStream\x12\x18.hamburger.ServerRequest\x1a\x19.hamburger.ActionResponse(\x010\x01\x12K\n" +
	"\x10serverStopStream\x12\x18.hamburger.ServerRequest\x1a\x19.hamburger.ActionResponse(\x010\x01B\x1fZ\x1dHamburger/app/connect;connectb\x06proto3"

var (
	file_hamburger_proto_rawDescOnce sync.Once
	file_hamburger_proto_rawDescData []byte
)

func file_hamburger_proto_rawDescGZIP() []byte {
	file_hamburger_proto_rawDescOnce.Do(func() {
		file_hamburger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hamburger_proto_rawDesc), len(file_hamburger_proto_rawDesc)))
	})
	return file_hamburger_proto_rawDescData
}

var file_hamburger_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_hamburger_proto_goTypes = []any{
	(*Empty)(nil),                // 0: hamburger.Empty
	(*StatRequest)(nil),          // 1: hamburger.StatRequest
	(*StatResponse)(nil),         // 2: hamburger.StatResponse
	(*StatMeta)(nil),             // 3: hamburger.StatMeta
	(*StatSummary)(nil),          // 4: hamburger.StatSummary
	(*StatusSummary)(nil),        // 5: hamburger.StatusSummary
	(*LatencySummary)(nil),       // 6: hamburger.LatencySummary
	(*TrafficSummary)(nil),       // 7: hamburger.TrafficSummary
	(*GCSummary)(nil),            // 8: hamburger.GCSummary
	(*StatSeries)(nil),           // 9: hamburger.StatSeries
	(*RequestSeriesPoint)(nil),   // 10: hamburger.RequestSeriesPoint
	(*TrafficSeriesPoint)(nil),   // 11: hamburger.TrafficSeriesPoint
	(*GCSeriesPoint)(nil),        // 12: hamburger.GCSeriesPoint
	(*SystemSeriesPoint)(nil),    // 13: hamburger.SystemSeriesPoint
	(*ProcessSeriesPoint)(nil),   // 14: hamburger.ProcessSeriesPoint
	(*DomainSummary)(nil),        // 15: hamburger.DomainSummary
	(*DomainSeriesPoint)(nil),    // 16: hamburger.DomainSeriesPoint
	(*ConnectionState)(nil),      // 17: hamburger.ConnectionState
	(*GeoResponse)(nil),          // 18: hamburger.GeoResponse
	(*DomainResponse)(nil),       // 19: hamburger.DomainResponse
	(*ConnResponse)(nil),         // 20: hamburger.ConnResponse
	(*HealthResponse)(nil),       // 21: hamburger.HealthResponse
	(*LoginRequest)(nil),         // 22: hamburger.LoginRequest
	(*LoginResponse)(nil),        // 23: hamburger.LoginResponse
	(*UserResponse)(nil),         // 24: hamburger.UserResponse
	(*User)(nil),                 // 25: hamburger.User
	(*UserUpdateRequest)(nil),    // 26: hamburger.UserUpdateRequest
	(*UserCreateRequest)(nil),    // 27: hamburger.UserCreateRequest
	(*UserDeleteRequest)(nil),    // 28: hamburger.UserDeleteRequest
	(*DomainServiceRequest)(nil), // 29: hamburger.DomainServiceRequest
	(*ServerRequest)(nil),        // 30: hamburger.ServerRequest
	(*ActionResponse)(nil),       // 31: hamburger.ActionResponse
	nil,                          // 32: hamburger.StatResponse.ConnectionsEntry
	nil,                          // 33: hamburger.StatMeta.CapabilitiesEntry
	nil,                          // 34: hamburger.GeoResponse.ValuesEntry
	nil,                          // 35: hamburger.DomainResponse.ValuesEntry
	nil,                          // 36: hamburger.ConnResponse.ValuesEntry
	nil,                          // 37: hamburger.HealthResponse.ValuesEntry
}
var file_hamburger_proto_depIdxs = []int32{
	3,  // 0: hamburger.StatResponse.meta:type_name -> hamburger.StatMeta
	4,  // 1: hamburger.StatResponse.summary:type_name -> hamburger.StatSummary
	9,  // 2: hamburger.StatResponse.series:type_name -> hamburger.StatSeries
	32, // 3: hamburger.StatResponse.connections:type_name -> hamburger.StatResponse.ConnectionsEntry
	15, // 4: hamburger.StatResponse.domains:type_name -> hamburger.DomainSummary
	16, // 5: hamburger.StatResponse.domain_series:type_name -> hamburger.DomainSeriesPoint
	33, // 6: hamburger.StatMeta.capabilities:type_name -> hamburger.StatMeta.CapabilitiesEntry
	5,  // 7: hamburger.StatSummary.status:type_name -> hamburger.StatusSummary
	6,  // 8: hamburger.StatSummary.latency:type_name -> hamburger.LatencySummary
	8,  // 9: hamburger.StatSummary.gc:type_name -> hamburger.GCSummary
	7,  // 10: hamburger.StatSummary.frontend_traffic:type_name -> hamburger.TrafficSummary
	7,  // 11: hamburger.StatSummary.backend_traffic:type_name -> hamburger.TrafficSummary
	7,  // 12: hamburger.StatSummary.total_traffic:type_name -> hamburger.TrafficSummary
	10, // 13: hamburger.StatSeries.requests:type_name -> hamburger.RequestSeriesPoint
	11, // 14: hamburger.StatSeries.traffic:type_name -> hamburger.TrafficSeriesPoint
	12, // 15: hamburger.StatSeries.gc:type_name -> hamburger.GCSeriesPoint
	13, // 16: hamburger.StatSeries.system:type_name -> hamburger.SystemSeriesPoint
	14, // 17: hamburger.StatSeries.process:type_name -> hamburger.ProcessSeriesPoint
	34, // 18: hamburger.GeoResponse.values:type_name -> hamburger.GeoResponse.ValuesEntry
	35, // 19: hamburger.DomainResponse.values:type_name -> hamburger.DomainResponse.ValuesEntry
	36, // 20: hamburger.ConnResponse.values:type_name -> hamburger.ConnResponse.ValuesEntry
	37, // 21: hamburger.HealthResponse.values:type_name -> hamburger.HealthResponse.ValuesEntry
	25, // 22: hamburger.LoginResponse.user:type_name -> hamburger.User
	25, // 23: hamburger.UserResponse.user:type_name -> hamburger.User
	17, // 24: hamburger.StatResponse.ConnectionsEntry.value:type_name -> hamburger.ConnectionState
	17, // 25: hamburger.ConnResponse.ValuesEntry.value:type_name -> hamburger.ConnectionState
	1,  // 26: hamburger.service.stat:input_type -> hamburger.StatRequest
	0,  // 27: hamburger.service.geo:input_type -> hamburger.Empty
	0,  // 28: hamburger.service.domain:input_type -> hamburger.Empty
	0,  // 29: hamburger.service.conn:input_type -> hamburger.Empty
	0,  // 30: hamburger.service.health:input_type -> hamburger.Empty
	22, // 31: hamburger.service.login:input_type -> hamburger.LoginRequest
	0,  // 32: hamburger.service.logout:input_type -> hamburger.Empty
	0,  // 33: hamburger.service.userGet:input_type -> hamburger.Empty
	26, // 34: hamburger.service.userUpdate:input_type -> hamburger.UserUpdateRequest
	27, // 35: hamburger.service.userCreate:input_type -> hamburger.UserCreateRequest
	28, // 36: hamburger.service.userDelete:input_type -> hamburger.UserDeleteRequest
	29, // 37: hamburger.service.serviceStart:input_type -> hamburger.DomainServiceRequest
	29, // 38: hamburger.service.serviceStop:input_type -> hamburger.DomainServiceRequest
	30, // 39: hamburger.service.serverRestart:input_type -> hamburger.ServerRequest
	30, // 40: hamburger.service.serverStop:input_type -> hamburger.ServerRequest
	1,  // 41: hamburger.service.statStream:input_type -> hamburger.StatRequest
	0,  // 42: hamburger.service.geoStream:input_type -> hamburger.Empty
	0,  // 43: hamburger.service.domainStream:input_type -> hamburger.Empty
	0,  // 44: hamburger.service.connStream:input_type -> hamburger.Empty
	0,  // 45: hamburger.service.healthStream:input_type -> hamburger.Empty
	22, // 46: hamburger.service.loginStream:input_type -> hamburger.LoginRequest
	0,  // 47: hamburger.service.logoutStream:input_type -> hamburger.Empty
	0,  // 48: hamburger.service.userGetStream:input_type -> hamburger.Empty
	26, // 49: hamburger.service.userUpdateStream:input_type -> hamburger.UserUpdateRequest
	27, // 50: hamburger.service.userCreateStream:input_type -> hamburger.UserCreateRequest
	28, // 51: hamburger.service.userDeleteStream:input_type -> hamburger.UserDeleteRequest
	29, // 52: hamburger.service.serviceStartStream:input_type -> hamburger.DomainServiceRequest
	29, // 53: hamburger.service.serviceStopStream:input_type -> hamburger.DomainServiceRequest
	30, // 54: hamburger.service.serverRestartStream:input_type -> hamburger.ServerRequest
	30, // 55: hamburger.service.serverStopStream:input_type -> hamburger.ServerRequest
	2,  // 56: hamburger.service.stat:output_type -> hamburger.StatResponse
	18, // 57: hamburger.service.geo:output_type -> hamburger.GeoResponse
	19, // 58: hamburger.service.domain:output_type -> hamburger.DomainResponse
	20, // 59: hamburger.service.conn:output_type -> hamburger.ConnResponse
	21, // 60: hamburger.service.health:output_type -> hamburger.HealthResponse
	23, // 61: hamburger.service.login:output_type -> hamburger.LoginResponse
	31, // 62: hamburger.service.logout:output_type -> hamburger.ActionResponse
	24, // 63: hamburger.service.userGet:output_type -> hamburger.UserResponse
	24, // 64: hamburger.service.userUpdate:output_type -> hamburger.UserResponse
	24, // 65: hamburger.service.userCreate:output_type -> hamburger.UserResponse
	31, // 66: hamburger.service.userDelete:output_type -> hamburger.ActionResponse
	31, // 67: hamburger.service.serviceStart:output_type -> hamburger.ActionResponse
	31, // 68: hamburger.service.serviceStop:output_type -> hamburger.ActionResponse
	31, // 69: hamburger.service.serverRestart:output_type -> hamburger.ActionResponse
	31, // 70: hamburger.service.serverStop:output_type -> hamburger.ActionResponse
	2,  // 71: hamburger.service.statStream:output_type -> hamburger.StatResponse
	18, // 72: hamburger.service.geoStream:output_type -> hamburger.GeoResponse
	19, // 73: hamburger.service.domainStream:output_type -> hamburger.DomainResponse
	20, // 74: hamburger.service.connStream:output_type -> hamburger.ConnResponse
	21, // 75: hamburger.service.healthStream:output_type -> hamburger.HealthResponse
	23, // 76: hamburger.service.loginStream:output_type -> hamburger.LoginResponse
	31, // 77: hamburger.service.logoutStream:output_type -> hamburger.ActionResponse
	24, // 78: hamburger.service.userGetStream:output_type -> hamburger.UserResponse
	24, // 79: hamburger.service.userUpdateStream:output_type -> hamburger.UserResponse
	24, // 80: hamburger.service.userCreateStream:output_type -> hamburger.UserResponse
	31, // 81: hamburger.service.userDeleteStream:output_type -> hamburger.ActionResponse
	31, // 82: hamburger.service.serviceStartStream:output_type -> hamburger.ActionResponse
	31, // 83: hamburger.service.serviceStopStream:output_type -> hamburger.ActionResponse
	31, // 84: hamburger.service.serverRestartStream:output_type -> hamburger.ActionResponse
	31, // 85: hamburger.service.serverStopStream:output_type -> hamburger.ActionResponse
	56, // [56:86] is the sub-list for method output_type
	26, // [26:56] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_hamburger_proto_init() }
func file_hamburger_proto_init() {
	if File_hamburger_proto != nil {
		return
	}
	file_hamburger_proto_msgTypes[13].OneofWrappers = []any{}
	file_hamburger_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hamburger_proto_rawDesc), len(file_hamburger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hamburger_proto_goTypes,
		DependencyIndexes: file_hamburger_proto_depIdxs,
		MessageInfos:      file_hamburger_proto_msgTypes,
	}.Build()
	File_hamburger_proto = out.File
	file_hamburger_proto_goTypes = nil
	file_hamburger_proto_depIdxs = nil
}
